### ISSUE TITLE
re-render form not smooth

### ISSUE THREAD

**Issue by shamanking** [formio/react#119]
When I re-render form of formio, it looks:

http://g.recordit.co/ZOX9ZDsAgw.gif

How can I make it smoother, or turn off loading when re-render

**Comment by randallknutson** [comment]
Your linked image no longer exists. Can you describe what is happening?

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!
