### ISSUE TITLE
FormBuilder - Text area not working

### ISSUE THREAD

**Issue by Drizin** [formio/react#123]
Created an empty project using create-react-app, and added FormBuilder. Dragging Text Area throws this error:

**utils.js:138 An error occured within custom function for wysiwyg TypeError: instance.wysiwygDefault is not a function**

Sample code:

```
import React, { Component } from 'react';
import {FormBuilder} from 'react-formio';

class App extends Component {
  render() {
    return (
      <div className="App">
        <FormBuilder 
			form={{ display: 'form' }} 
      </div>
    );
  }
}

export default App;

```

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
