### ISSUE TITLE
Module not found: Error: Can't resolve, Please help me with this

### ISSUE THREAD

**Issue by misterharshith** [formio/react#126]
### formiojs v2.32.3, react-formio v2.1.1, node v8.11.4 and npm 5.6.0 
Im getting following error when I execute npm run serve

ERROR in ./~/react-formio/lib/modules/auth/containers/Login.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/auth/containers'
 @ ./~/react-formio/lib/modules/auth/containers/Login.js 11:14-51
 @ ./~/react-formio/lib/modules/auth/routes.js
 @ ./~/react-formio/lib/modules/auth/index.js
 @ ./src/app/auth/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/auth/containers/Register.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/auth/containers'
 @ ./~/react-formio/lib/modules/auth/containers/Register.js 11:14-51
 @ ./~/react-formio/lib/modules/auth/routes.js
 @ ./~/react-formio/lib/modules/auth/index.js
 @ ./src/app/auth/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/Edit.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/Edit.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/View.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/View.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/Create.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/Create.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

**Comment by AhmedSayed77** [comment]
replace this line 
```javascript
import { Formio } from "react-formio";
```
with this one
```javascript
import { Form } from "react-formio";
```

**Comment by areaeuro** [comment]
@AhmedSayed77  Your changes do not fix the issue mentioned.

Only found that line in src/app/views/Home.js
Changing as suggested gives the following ADDITIONAL errors on `npm run serve,` but the errors stated by @Harshithharry are not fixed.

> ERROR in ./src/app/views/Home.js
>
>/mnt/windows-home/Users/Rick/John/Web Stuff/formio/exampleAPPS/react-app-starterkit/src/app/views/Home.js
>   3:9   warning  'Form' is defined but never used  no-unused-vars
>  26:16  error    'Formio' is not defined           react/jsx-no-undef

After reading this issue, https://github.com/formio/react-app-starterkit/issues/3
Changing package.json from 
`"react-formio": "^2.0.0-beta1",`
to 
`"react-formio": "2.0.5",`
and then from root directory of app
`npm update && npm install && npm run serve`
Worked for me.

**Comment by 9064444169** [comment]
./src/components/signin/signin.js
Module not found: Can't resolve './signin/pages/signupform' in 'C:\Users\Admin\Desktop\Tours\darj\src\components\signin'


please help me

**Comment by surendrarayamajhee** [comment]
Module not found: Error: Can't resolve './components/order/DeliveryEnquiry' in '/media/suren/G/new/hub/resources/js
in vue   js

**Comment by surendrarayamajhee** [comment]
ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/DeliveryEnquiry' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 58:13-58
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/current-order.vue' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 38:13-60
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/failed-transaction-order.vue' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 48:13-71
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/order-list' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 33:13-53
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/orderList' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 53:13-52
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/return.vue' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 63:13-53
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve './components/order/unsigned-address.vue' in '/media/suren/G/new/hub/resources/js'
 @ ./resources/js/route.js 43:13-63
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by MohittPattel** [comment]
I got the same problem while install 3d react carouselal

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
