### ISSUE TITLE
Please guide me how to implement this on my react project

### ISSUE THREAD

**Issue by misterharshith** [formio/react#128]
Hello,

Can you please guide me how to implement this on my react project, I'm confused as its mentioned only few lines to get a formbuilder, but i need to customize the whole components inside project and react-app-starterkit isn't working as its trowing module not found error.

Thanks in Advance
Harshith

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
