### ISSUE TITLE
Not working properly with bootstrap 4.x.x

### ISSUE THREAD

**Issue by abhisheksdm** [formio/react#130]
Hi
my project build in bootstrap 4 react js when i used this form builder in our project with out using bootstrap 3 cdn link its not working properly design messy and not show Glyphicon icon and when i used with bootstrap 3. its effects my other pages because i am using bootstrap 4.
please suggest any solution form that how i can use react-formio with bootstrap 4

**Comment by AnirudhaGohokar** [comment]
Hi Team,

Any update on this. There is some compatibility issue with bootstrap and making this library unusable on production.

Thanks,
Anirudha

**Comment by travist** [comment]
It should be working with the latest version. Let us know otherwise.
