### ISSUE TITLE
Please provide a list of props for Formbuilder

### ISSUE THREAD

**Issue by abhisheksdm** [formio/react#131]
Please provide a list of props for Formbuilder, for example how to  give predefined data for the formbuilder to show.
Thanks in advance

**Comment by sireeshav** [comment]
Yes I need it too.. Please help soon

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
