### ISSUE TITLE
Multiple calls of onSubmit handler

### ISSUE THREAD

**Issue by jegatheesh95** [formio/react#135]
Hi, I passed onSubmit handler to form component to call an external API. When submitted the form, the onSubmit handler is called multiple times. No form data is available for first two calls.

**Comment by sireeshav** [comment]
@jegatheesh95 did u get the fix..? I need it too

**Comment by jegatheesh95** [comment]
> @jegatheesh95 did u get the fix..? I need it too

I wrapped  the formio.js with cusom react component instead of using react-formio. The issue is only on react-formio.

**Comment by randallknutson** [comment]
Is there something we need to fix in our implementation that would resolve this? We can take a look at it but this would help us fix this faster.

**Comment by Andrey-Pavlov** [comment]
It still triggers onSubmit multiple times. Any workarounds?
```
const onSubmit = (submission) => {
  };
      <Form form={form}
            submission={submission}
            onSubmit={onSubmit}
      />

```
![image](https://user-images.githubusercontent.com/7976740/78789016-3dbc1800-79b5-11ea-9814-ec790fa489ff.png)

**Comment by wag110894** [comment]
Hello @Andrey-Pavlov,

What version of react-formio are you running?

**Comment by Andrey-Pavlov** [comment]
"formiojs": "4.9.15",

**Comment by wag110894** [comment]
@Andrey-Pavlov,

We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please contact support@form.io if you would like the price to expedite this for you.

Thank you,

William Gay

**Comment by Andrey-Pavlov** [comment]
Sometimes it works as expected (**1** call) but in other cases it calls submitHandler **4** times.

**Comment by j-perl** [comment]
If that helps: this happens only when I pass an options object to the <Form /> component. Otherwise, it works as expected.

**Comment by JovanT** [comment]
dears the issue is in double call of this.initializeFormio(); once in componentDidMount second time in componentWillReceiveProps,
and this is only when we change the form and we open for the frist time the second time if (form !== nextProps.form) not leting double registration.

**Comment by wag110894** [comment]
Hello all,

This issue has actually been resolved on our 4.12.0 build of formio.js. You will need to make change to your package.json and you will see this issue resolved.

**Comment by tunggao** [comment]
@wag110894 Hi, Although I upgraded formio.js to version 4.12.0,  my function onSubmit still call multiple 4 times, I had console.log my data and it's displayed 4 times. Could you have any solution ?. Thanks a lot!

![issues_screen21](https://user-images.githubusercontent.com/31013999/98194551-3d3b2e00-1f52-11eb-8eb5-f6af2842c37f.png)

**Comment by turgaygulmez** [comment]
We are having the same problem. Submit handler is being called 4 times? First two calls does not contain the updated form data but last two does. Can you please resolve the issue since its very critical?

**Comment by wag110894** [comment]
@turgaygulmez, where are you experiencing this issue? Locally or hosted by us? Can you provide a video as well as a form embed to help us replicate?

**Comment by RishikeshVedpathak** [comment]
I was facing the same. There were multiple calls for the onSubmit handler.
I was using version react-formio `4.3.0`.
It seems to be resolved after upgrading to version `5.0.0-rc.2`

**Comment by acordobamo** [comment]
Hi, I currently have the same problem. I am using version 5.1.1. Is there a solution for this?

**Comment by megaxayda** [comment]
I use ref to refer to a boolean and stop the second submission, but it's temporary tho. At least it's working.
![image](https://user-images.githubusercontent.com/20489253/233595892-1a44acb1-866c-4932-a4f9-97e2f321c17b.png)

**Comment by Andrey-Pavlov** [comment]
Hello. It was 3 years since my previous comment and it is sad that the issue was not fixed. I changed different projects, have a little daughter and never used Formio anymore. I wish everyone the best, the dark streak in life will pass.
