### ISSUE TITLE
Form builder doesn't support button action 'save in state'

### ISSUE THREAD

**Issue by cohesivejones** [formio/react#140]
**Libraries**
node v8.9.1
yarn v1.3.2
react-formio v3.0.1
react v16.3.1

**Description**
Form builder doesn't currently support button action 'save in state' where a user can provide a custom submission state or 'draft' if they do not wish to execute validations.

**Comment by wag110894** [comment]
Hello Nathan,

Thank you for the the feedback. We have the feature that allows the ‘save in state’ button to function on our roadmap for the new core builder.   We will let you know when that is complete or I can get a quote to expedite that for you if you are interested.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by johhansantana** [comment]
how could we use this library with something like http://formio.github.io/formio.js/app/examples/savedraft.html

I don't see anything for drafts in this library.

**Comment by travist** [comment]
The savedraft would just need to be enabled in your application. I don't believe this library exposes it, but this library does expose the "core" renderer instance which you could set Draft mode directly on that and it should work.

**Comment by johhansantana** [comment]
@travist could you provide an example on how to enable this in a react application? I have tried using something like:

```jsx
<Form src="..." options={{saveDraft: true}} />
```

But I'm not sure if this is the correct way to do it since it doesn't really do anything on my end or I'm actually doing it the wrong way.

**Comment by randallknutson** [comment]
We probably need to change the shape of the options attribute to allow for this option or just make it a generic object. 

https://github.com/formio/react-formio/blob/master/src/components/Form.js#L15-L20

**Comment by aryanisml** [comment]
Is there any option or any example to implement saveDraft in react application ??? SaveDraft is only working with form builder server or we can use with any server.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
