### ISSUE TITLE
npmjs don't have latest version 4.0.0 of react-formio

### ISSUE THREAD

**Issue by abhisheksdm** [formio/react#141]
Hello Team,
I am unable to install react-formio V4.0.0 on my system using npm. Please publish latest build on npmjs ASAP.
Thank you in advance.

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out! 

React-formio v4 is currently in alpha so it will not automatically install when using npm. You will need to use "npm install react-formio@4.0.0-alpha.1" to get it.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by abhisheksdm** [comment]
Thanks @wag110894 , as per suggested by you, i am able to install react-formio@4.0.0-alpha.1 in  my project but it giving some console errors to me.

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out!  We are working hard on the 4x branch and will do a beta release as soon as possible.   In the meantime, I would recommend going with our 3.x release. 

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by abhisheksdm** [comment]
Thanks for you valuable feedback, it is working fine with 3.X release but i am using bootstrap 4 in out project but react-formio is using version 3.X of bootstrap, so there are some design related issues that i am facing.Please let me know that you are releasing 4.x branch with bootsrtap 4 or 3 ?
Thank you very much

**Comment by wag110894** [comment]
Hello Again, 

React-formio 3.x. branch is compatible with bootstrap 4. What kind of issues are you facing with the design?  

We are still working on our 4.x. Branch.You are able to use either bootstrap 3 or 4.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by abhisheksdm** [comment]
HI William Gay,
Thanks for your reply
Actually I am facing UI Issues like if we are using bootstrap 3 the form fields, icons, and buttons looks perfect but when we are change the bootstrap 3 to bootstrap 4 the fields, and icons alignment not  ijn proper format and there is difference 3 and 4 glyphicon icons also some icons not show. 
I have attach below screen shoots so you  can understand easily because there is some difference between 3 and 4 bootstrap classes. and we are not using bootstrap 3 so please suggest some solution for bootstrap 4 version.

1.  ![image](https://user-images.githubusercontent.com/32297964/47336609-0ddc6000-d6ae-11e8-9256-31081671c2a9.png)


2.  ![image](https://user-images.githubusercontent.com/32297964/47336622-1e8cd600-d6ae-11e8-8eb2-56c46e317871.png)

**Comment by wag110894** [comment]
Hello Again,

Your screenshots definitely look incorrect but it appears to be that you are not including bootstrap correctly. Here is an example of our form builder working correctly in bootstrap 4. https://formio.github.io/formio.js/app/builder 

Please let me know if you have any further questions or concerns.

Thanks,
William Gay 
Form.io Developer Support

**Comment by vishaldenzil** [comment]
wizard is supported in form builder??

**Comment by abhisheksdm** [comment]
Hello William Gay, thanks for your support.
The example you provided is built with form.io, but i am using react-formio V3.0.3. and in that version i am facing issues because here glyph-icons are used but in the example that you had shown to me is using fa-fa icons.
Please provide suggestion to clear my scenario.
Thanks

**Comment by randallknutson** [comment]
To switch to use font awesome, you can add it as an options setting:
<Form options={icons: 'fontawesome'} />

In addition, the react renderer wraps the formio.js library and uses it to render the form. That is why the css from formio.js needs to be included.
