### ISSUE TITLE
how can we edit forms already built using formbuilder 

### ISSUE THREAD

**Issue by vishaldenzil** [formio/react#148]
form builder issue

**Comment by vishaldenzil** [comment]
I have created form using formbuilder. I have the json data of the form. I want to edit the same form which i was created earlier using form builder. Instead of creating it again .

**Comment by randallknutson** [comment]
You can set it as the form attribute of the form builder component instead of the default.

For example, load the form into the myform variable and then:
```
ReactDOM.render(
  <FormBuilder form={myform} onChange={(schema) => console.log(schema)} />
  , document.getElementById('builder')
);
```

**Comment by vishaldenzil** [comment]
Thanks @randallknutson

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
