### ISSUE TITLE
Rendering Form builder duplicates component palette on setState

### ISSUE THREAD

**Issue by perman26** [formio/react#150]
duplicates component palette after changing state because of re render.

**Comment by randallknutson** [comment]
Can you provide a form or some steps to reproduce this?

**Comment by perman26** [comment]
```
import React, { Component } from 'react';
import {FormBuilder} from 'react-formio';

class App extends Component {

onChangeFormBuilder(schema){
 this.setState({ schema: schema });
}

  render() {
    return (
      <div className="App">
        <FormBuilder 
			form={{ display: 'form' }} 
			onChange={(schema) => this.onChangeFormBuilder(schema)} />
      </div>
    );
  }
}
export default App;
```

When we change state after onchange, it duplicates component palette

**Comment by vishaldenzil** [comment]
Even am also facing the same problem. Even i need it too.

**Comment by vishaldenzil** [comment]
import React, {Component} from "react";
import {FormBuilder} from 'react-formio';
import './index.css';
import $ from 'jquery';
import * as axios from 'axios';
import {routes} from './routes'

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
		schema:{},
    display:"form",
    name:""
	 }
  this.handleData=this.handleData.bind(this);
	this.save=this.save.bind(this);
  this.handleChange=this.handleChange.bind(this);
  this.formName=this.formName.bind(this);
  }
  handleChange(e)
  {
	this.setState({ display: e.target.value });
  }
  formName(e)
  {
    this.setState({ name: e.target.value });
  } 
  handleData(e)
  {
    this.setState({schema:JSON.stringify(e)});

  }

  
  shouldComponentUpdate(nextProps, nextState)
  {
	
	 if(nextState.display === this.state.display)
	 {
		return false;
	 }
	 else
	 {
		 return true;
	 }
  }

  render() {
     const display=this.state.display ==="form";
      return (
     <div>
         <div class="form-group">
          <label for="sel1">Select type:</label>
          <div></div>
          <div>
            <select  onChange={this.handleChange} class={{width:50}}>
              <option value="form">form</option>
              <option value="wizard">wizard</option>
            </select>
          </div>
  
         </div>
	
        {display ?  ( <FormBuilder 
        form={{display: 'form'}} 
        onChange={this.handleData}
        options={{ readOnly: true}}
        />) :  ("")}
       
        {display ? ("") : ( <FormBuilder 
        form={{display: 'wizard'}} 
        onChange={this.handleData}
        options={{ readOnly: true}}/>) }

        
     {/* <Values form="wizard" /> */}
     <div>
       <button className="btn btn-primary" onClick={this.save}> submit</button>
     </div>
    </div> 
      )
  }
}
export default FormIoCreation;

**Comment by vishaldenzil** [comment]
This way i tried to solve problem. This is not good way i feel ._

import React, { Component } from "react";
import { FormBuilder } from "react-formio";
import * as axios from "axios";
import { routes } from "./routes";

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
      schema: {},
      display: "form",
      name: ""
    };
    this.handleData = this.handleData.bind(this);
    this.save = this.save.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.formName = this.formName.bind(this);
  }
  handleChange(e) {
    this.setState({ display: e.target.value });
  }
  formName(e) {
    this.setState({ name: e.target.value });
  }
  handleData(e) {
    this.setState({ schema: JSON.stringify(e) });
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (nextState.display === this.state.display) {
      return false;
    } else {
      return true;
    }
  }

  render() {
    const display = this.state.display === "form";
    return (
      <div>
        <div class="form-group">
          <label for="sel1">Select type:</label>
          <div />
          <div>
            <select onChange={this.handleChange} class={{ width: 50 }}>
              <option value="form">form</option>
              <option value="wizard">wizard</option>
            </select>
          </div>
        </div>

        {display ? (
          <FormBuilder
            form={{ display: "form" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        ) : (
          ""
        )}

        {display ? (
          ""
        ) : (
          <FormBuilder
            form={{ display: "wizard" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        )}

        <div>
          <button className="btn btn-primary" onClick={this.save}>
            {" "}
            submit
          </button>
        </div>
      </div>
    );
  }
}
export default FormIoCreation;

**Comment by vishaldenzil** [comment]
This way am currently avoiding the problem .This is not good way.

import React, { Component } from "react";
import { FormBuilder } from "react-formio";
import * as axios from "axios";
import { routes } from "./routes";

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
      schema: {},
      display: "form",
      name: ""
    };
    this.handleData = this.handleData.bind(this);
    this.save = this.save.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.formName = this.formName.bind(this);
  }
  handleChange(e) {
    this.setState({ display: e.target.value });
  }
  formName(e) {
    this.setState({ name: e.target.value });
  }
  handleData(e) {
    this.setState({ schema: JSON.stringify(e) });
  }

  shouldComponentUpdate(nextProps, nextState) {
    if (nextState.display === this.state.display) {
      return false;
    } else {
      return true;
    }
  }

  render() {
    const display = this.state.display === "form";
    return (
      <div>
        <div class="form-group">
          <label for="sel1">Select type:</label>
          <div />
          <div>
            <select onChange={this.handleChange} class={{ width: 50 }}>
              <option value="form">form</option>
              <option value="wizard">wizard</option>
            </select>
          </div>
        </div>

        {display ? (
          <FormBuilder
            form={{ display: "form" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        ) : (
          ""
        )}

        {display ? (
          ""
        ) : (
          <FormBuilder
            form={{ display: "wizard" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        )}

        <div>
          <button className="btn btn-primary" onClick={this.save}>
            {" "}
            submit
          </button>
        </div>
      </div>
    );
  }
}
export default FormIoCreation;

**Comment by vishaldenzil** [comment]
@sireeshav thank you,
Am passing the data to form builder  "form" props  . If i pass through  through api its not taking that data.

     <FormBuilder 
        form={this.state.form} 
        onChange={this.handleData}
        /><FormBuilder 
        form={this.state.form} 
        onChange={this.handleData}
        />
If i set to form state through  constructor  its displaying the form . If i set through setState its giving the problem. I can say its not rendering again .

**Comment by vinayxooa** [comment]
Same issue with me. If state is set onChange then multiple pallets appear.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
