### ISSUE TITLE
type "content" not rendering 

### ISSUE THREAD

**Issue by perman26** [formio/react#156]
type "content" is visible in form builder but when we render using schema in react component, it is not displaying text-editor

**Comment by randallknutson** [comment]
Sorry for the confusion but the content component is for adding html type content that displays on the form. If you want the wysiwyg text editor in the form, use the textarea component with the setting for wysiwyg.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
