### ISSUE TITLE
Moving the existing components ,It doesn't trigger onChange event.

### ISSUE THREAD

**Issue by vishaldenzil** [formio/react#162]
I am reshuffling components  ...
Eg. changing the position of text box and email field.. onChange  function is not triggering .

**Comment by randallknutson** [comment]
Looks like we are missing the event emit when a component is moved. It would go here: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L874-L900

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
