### ISSUE TITLE
In Date/Time Component Data is not working

### ISSUE THREAD

**Issue by aman251196** [formio/react#163]

**Comment by aman251196** [comment]
In Date/Time Component when I click on Data field, its not working. Other fields like Validation, logic is working but Data is not.

**Comment by randallknutson** [comment]
Is this a result of an old version of formio.js? Try manually updating to the latest and see if it works.

**Comment by aman251196** [comment]
Currently we are version  "react-formio": "^2.1.1" ...check if this the correct version..if it is then provide us the solution.

**Comment by travist** [comment]
Type the following within your project folder.

```
npm install formiojs
```

This should bring in the latest core renderer which does resolve this problem. If that works, then it should work if you delete your node_modules and reinstall a fresh dependency list.

**Comment by bayyamsandeep** [comment]
In the Date/Time Component when I click on the Input field or icon Calender is not Opening. Currently, I am using @formio/react 5.2.3 and Formio.js 4.14.8.

**Comment by bayyamsandeep** [comment]
![FormioCalendar](https://user-images.githubusercontent.com/101857028/183075059-f2c12861-52ef-41ac-a721-df4f908ee237.png)

**Comment by bayyamsandeep** [comment]
I am missing an input element with a class name form-control active. I have no idea why I am missing that input

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
