### ISSUE TITLE
reload option on each render 

### ISSUE THREAD

**Issue by perman26** [formio/react#164]
I have used select with URL as data in modal.  select loading options correctly first time.

I want to reload options and call API again, if I open modal again.

**Comment by randallknutson** [comment]
We don't currently have an option to reload the options each time the select is opened. We cache those values on the front end. If you add "Refresh On" to the select to "All changes" and Lazy Load to true it may work.

**Comment by perman26** [comment]
It is not working.............

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
