### ISSUE TITLE
Display PDF not working

### ISSUE THREAD

**Issue by sireeshav** [formio/react#165]
ReactDOM.render(
  <FormBuilder form={{display: 'pdf'}} onChange={(schema) => console.log(schema)} />
  , document.getElementById('builder')
);

Or 
ReactDOM.render(
  <FormBuilder form={{display: 'pdf',components}} onChange={(schema) => console.log(schema)} />
  , document.getElementById('builder')
);

I am trying to render a pdf form using my components which were created using form builder. But nothing is showing up. Please help.

**Comment by travist** [comment]
We will take a look.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
