### ISSUE TITLE
Form Builder crashes when building a large form in Wizard mode in Windows but does not crash when building in a mac 

### ISSUE THREAD

**Issue by rpsperera** [formio/react#169]

**Comment by wag110894** [comment]
Hello @RukshanPrabudda,

This is William with the Form.io support team. Thanks for reaching out! 

We are having no issues with building Wizards on Windows 10.  Which version of Windows are you using? Could you clarify what you mean by 'crashes when building'? Is it allowing you to save the Wizard form?

Please let me know.

Thanks, 
William Gay
Form.io Support

**Comment by prem911** [comment]
I m seeing huge memory consumption. In macOS, the chrome tab reported 5.8GB of memory when I was editing a form

**Comment by travist** [comment]
what version of the core renderer are you using.

**Comment by prem911** [comment]
We are using react-formio@3.1.12 which internally uses "formiojs": "^3.16.1"

**Comment by duanlixia** [comment]
Hi ~  Is there any progress?

**Comment by randallknutson** [comment]
We've made some improvements lately with the latest 3.x branch. In addition, you can checkout the beta version of 4.x branch of formio.js. It has a significantly reworked rendering system that is proving to be much more performant.

**Comment by prem911** [comment]
We are right now using 3.1.12. When can we expect the changes in the 3.x branch?

**Comment by randallknutson** [comment]
If you install formiojs manually (npm install --save formiojs) it will update the version that is used by react-formio. This doesn't require a new release of react-formio.
