### ISSUE TITLE
Prefix are not displayed in read-only mode. 

### ISSUE THREAD

**Issue by aman251196** [formio/react#177]
I have added prefix of Rupee(₹) sign as prefix in some form fields such as Rate , Total Taxable value etc. When I am seeing it on read-only mode Its not displaying the prefix. kindly provide us the solution for it.

**Comment by travist** [comment]
The "prefix" is for the field and not the data as it is being displayed. This sounds like what you are asking for is the "currency" component which I do believe places the currency symbol next to the data as it is being displayed in the data tables. Let me know otherwise.

**Comment by aman251196** [comment]
Thanks for your reply, actually I want to preview prefix for the fields in the read-only mode..i.e Prefix should be there on the field in the read-only as it is being shown in the actual form.

**Comment by randallknutson** [comment]
Can you send an example form so we can look at it? In our testing it appears to be working for us.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
