### ISSUE TITLE
There are not types available to use it with typescript

### ISSUE THREAD

**Issue by dheerajsh** [formio/react#184]
I wanted to use it with my typescript-react project but can not use it because types are not available for the lib.

**Comment by randallknutson** [comment]
We are starting to use typescript in various applications. We'd appreciate your help in adding them if you are able.

**Comment by peisenmann** [comment]
Is someone actively working on the type definitions? I would consider contributing, but I don't want to step on anyone's toes to do it.

**Comment by travist** [comment]
Nobody from Form.io is actively working on this so we would GREATLY appreciate your contribution!

**Comment by BrianHey** [comment]
me too

**Comment by mm-dsibinski** [comment]
+1 for React Types 🙂

**Comment by dheerajsh** [comment]
@travist Sorry for the very late reply is it still valid?. I can add types if yes.

**Comment by dheerajsh** [comment]
@travist is it still valid?.  I have been using some type's declaration to support it with my typescript application. I would like to add them here.

**Comment by randallknutson** [comment]
The 5.x branch of formio.js uses the typescript compiler now! When we go to 5.x for react-formio, which shouldn't be too much longer, I will switch the compiler to use typescript as well. That should include all the types from formio.js.

**Comment by dheerajsh** [comment]
Sounds good, what about the react component types.?

**Comment by randallknutson** [comment]
Those will be included with the switch of react-formio to using the typescript compiler.

**Comment by mm-dsibinski** [comment]
I also installed the newest https://www.npmjs.com/package/@formio/react, but can't use it with TypeScript because of no typings..

**Comment by jafin** [comment]
@randallknutson 
> The 5.x branch of formio.js uses the typescript compiler now! When we go to 5.x for react-formio, which shouldn't be too much longer, I will switch the compiler to use typescript as well. That should include all the types from formio.js.

I could not see any active typescript compiler being used. So I added Typescript to generate the typedefs only, and made a PR.  I haven't covered all the types (via jsdoc annotations) , and some maybe wrong, but it's a start and was enough for me to integrate into an existing project.

Are you interested in moving the project itself to typescript? I may have some time I can commit in the next few weeks to see if I can help?

**Comment by jessetcofie** [comment]
Anyone still looking for a fully wrapped TS implementation can try [@tsed-formio](https://github.com/tsedio/tsed-formio).

**Comment by TanyaGashtold** [comment]
Some types were added to the @formio/react library. If you need something else, your contribution will be appreciated. I am closing the issue as it was created too long ago and there are no new comments here. Thanks!
