### ISSUE TITLE
Issue with conditional logic

### ISSUE THREAD

**Issue by prem911** [formio/react#185]
To see the problem, run this
https://codesandbox.io/s/wn03z9vj45
On the right side, see the console.
The button is getting pressed and the data is being set.
However the number box is not reacting to this change.

The similar example is done in form.io. This uses the simple form.io js plugin.
Here is the public url to it.
https://formview.io/#/rdoeoqmbmkxsttz/frm1?header=1

What is going wrong with the react component?

**Comment by randallknutson** [comment]
In more recent versions of the renderer, which react-formio uses, the button component sets itself to "true" if pressed. This is overriding the "test" value you are setting. You should just check for a boolean value for the button.

**Comment by prem911** [comment]
We are using react-formio@3.1.12
I was setting the button to a string value 'test'. Removed that.
The console log shows that on button press, it is set to true.

However, the conditional logic for number field is not triggered and the number field remains hidden.
There is a console log for the custom conditional code and it is not trigger when the button is pressed.

I have repeated the same example in form.io 
https://formview.io/#/rdoeoqmbmkxsttz/frm1?header=1
Here the button takes any arbitrary value on pressed and this gets persisted and used in the custom condition for the number field.

So, in my opinion there is definitely a difference of behavior in both the libraries.

**Comment by randallknutson** [comment]
Yes, our portal is using a much older version of the renderer (angularjs version) that we are planning on replacing soon with the same one react-formio uses. Having a button press show fields is not something we've seen a lot of people do. You can trigger off of a radio button or checkbox and that should work just fine. If you need to have the functionality work with buttons, we would accept a pull request to add/fix the functionality or we could get you on a support contract to look into it for you.

**Comment by prem911** [comment]
We started off with checkbox, it didnot work so we thought button will be a workaround.
However, both dont work.

**Comment by randallknutson** [comment]
What didn't work with the checkbox? We use this all the time to show additional fields when the box is checked or unchecked.

**Comment by prem911** [comment]
I will share one example where condition on checkbox was not working.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
