### ISSUE TITLE
"Required" Text Inputs Allow Only Spaces as Valid

### ISSUE THREAD

**Issue by bacon1986** [formio/react#188]
When filling in a form on form.io itself, a series of spaces is not valid for a required text field or text area. This is as expected:
![image](https://user-images.githubusercontent.com/7498263/57443650-7358fe00-7246-11e9-8429-6d5e60f497dc.png)

When filling in the same form in a react app using react-formio this same input is considered valid and the submission is allowed. This is not as expected:
![image](https://user-images.githubusercontent.com/7498263/57443724-a3080600-7246-11e9-9870-dc35913ccc0f.png)

Thanks

**Comment by bacon1986** [comment]
react-formio verson: 3.1.12
formio version: Github 1.17.4

**Comment by randallknutson** [comment]
Thanks for the find! This does look like an issue in the newer version of our renderer. AngularJs is probably doing a trim() on the input before it goes to validation. We should probably do something similar on newer versions. Is this something you could fix or would you like to wait for us to fix?

**Comment by bacon1986** [comment]
I'm happy to wait for now as I've got other things to work on as well but if I finish all of those I may see if I can have a look.

Thanks

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
