### ISSUE TITLE
Custom default value does not work when the text field has conditional logic

### ISSUE THREAD

**Issue by chenyil** [formio/react#189]
Form definition JSON:

{
    "display": "form",
    "components": [
        {
            "label": "Show hidden field",
            "shortcut": "",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "checkbox",
            "input": true,
            "key": "showHiddenField",
            "defaultValue": false,
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "customConditional": "",
            "logic": [],
            "properties": {},
            "reorder": false,
            "encrypted": false
        },
        {
            "label": "prefix",
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "prefix",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "properties": {},
            "widget": {
                "type": ""
            },
            "reorder": false,
            "inputFormat": "plain",
            "encrypted": false,
            "customConditional": "",
            "logic": []
        },
        {
            "label": "hidden field",
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "hiddenField",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "true",
                "when": "showHiddenField",
                "json": "",
                "eq": "true"
            },
            "properties": {},
            "inputFormat": "plain",
            "encrypted": false,
            "customConditional": "",
            "logic": [],
            "tags": [],
            "customDefaultValue": "value = data['prefix'] +'-';",
            "widget": {
                "type": ""
            },
            "defaultValue": "-",
            "reorder": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

Expected behaviour:
1. type something in "prefix" field
2. check the checkbox
3. The text field should display a default value

However, the text field's custom default value doesn't seem to do anything. Is this a bug in form.io for react-formio?

Thanks!

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
