### ISSUE TITLE
FormBuilder with PDF

### ISSUE THREAD

**Issue by austindbertola** [formio/react#194]
I am passing a PDF form definition to the FormBuilder component and everything gets rendered correctly. However, when I drag a component onto the form, nothing happens. If I pass in a regular form definition, the “new comment” pop up shows up when dragging over a component. Does the PDF builder work with this library? Does it require any additional configurations or libraries in order to work?

**Comment by austindbertola** [comment]
So this event listener is working: https://github.com/formio/formio.js/blob/43ec83360795986a5b48a3ebe41048e776c72dc9/src/PDFBuilder.js#L159. And so is the one above it on line 158. This event listener is not: https://github.com/formio/formio.js/blob/43ec83360795986a5b48a3ebe41048e776c72dc9/src/PDFBuilder.js#L48 and neither is the one on line 44. On line 159 if I change the code to execute ```this.dragStop(event)``` instead of ```this.disableDropZone()``` it works. I don't think this is specific to the react-formio component, so should I move this issue?

Even still, any help with this would be greatly appreciated. It doesn't feel right to make that code change. I am assuming y'all have had it working the way it is written, but maybe I am missing something.

**Comment by wag110894** [comment]
Thanks for reaching out!
We have added this item to our backlog and will discuss this in our Weekly Planning Meeting.

Thanks.

**Comment by austindbertola** [comment]
It looks like this must be a CSS issue. The formio-drop-zone css class has position absolute. If I remove that, it works, but the pdf disappears into the background on drag. So the "drop" event isn't getting triggered because I guess the draggable element isn't getting passed to it. Though now, I am not sure why/how my CSS is messing things up. I am including every CSS file on the page `import 'react-formio/node_modules/formiojs/dist/formio.full.css';
import 'react-formio/node_modules/formiojs/dist/formio.form.css';
import 'react-formio/node_modules/formiojs/dist/formio.builder.css';`

**Comment by austindbertola** [comment]
Also I get uncaught type error on parent.addComponentTo

The WebFormBuilder expects (schema, parent, ... https://github.com/formio/formio.js/blob/43ec83360795986a5b48a3ebe41048e776c72dc9/src/WebformBuilder.js#L864

The PDFBuilder is passing (parent, schema ... https://github.com/formio/formio.js/blob/43ec83360795986a5b48a3ebe41048e776c72dc9/src/PDFBuilder.js#L85

I'm thinking that is not correct.

**Comment by austindbertola** [comment]
This also is only working on v3.20.0 form formiojs. If I upgrade to 3.20.16, when I load the PDF form into the FormBuilder, the "spinner icon" never leaves the pdf document

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
