### ISSUE TITLE
MultiForm flow with PDF not working

### ISSUE THREAD

**Issue by austindbertola** [formio/react#196]
I am following the example found here: http://formio.github.io/formio.js/app/examples/multiform.html

I have created 3 forms. One is the parent form which has 2 "nested forms". 1 of the nested forms is a PDF form, and the other is a regular Web Form. I have configured a field on each of these forms that should get its "default value" from a field in the parent form. This is working for the Web Form, but not for the PDF Form. In my react application, I am simply using the Form component to render the form. Any ideas what I could be doing wrong or if this is a known issue? I added a "console.log(data)" in each of the fields' Default Value field. For the Web Form, the last console.log has my parent value in it. What's weird, is for the PDF Form, I see the parent value logged in the console but then 3 more logs occur with empty objects. So it is like at some point the data is getting overwritten in a background process.

I also think it is worth noting that when I try this form from the portal preview page, this behavior is very different. The PDF form actually works, it gets the value defaulted. And the Web Form "data" object in the console looks a lot different. I would expect the portal preview and using this library to embed the form would work the same.

**Comment by randallknutson** [comment]
What version of react-formio are you using? I don't believe pdf is finished in 4.x yet.

**Comment by austindbertola** [comment]
I am using react-Formio 3.1.12, which I believe is the latest 3.x version

**Comment by randallknutson** [comment]
I'm really not sure what is going on. The functionality should be working in 3.x. Can you provide more context or information about your form and what is going wrong?

**Comment by austindbertola** [comment]
Hi @randallknutson, thanks for the responses and help. So it is actually very easy to reproduce. I have simply copied down the formio react example application and created a basic project with the Event form. I also uploaded a new PDF form and added a single field called **pdfTitle**. This fiield has the following property: `"calculateValue": "console.log(data);\nvalue = data.childPDFTitle;"`

In the Event form I added a Select box with a single option "contract". I then made the form a Wizard and added a new panel called "Contract". This panel will only display when the select box is "contract". I then added the PDF form as a nested form in that panel. In the nested form properties, I have this: `"customDefaultValue": "value = {data: {childPDFTitle: data.title}}"`

Now, when I run this from the portal, I see these logged in the console:
`{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: ""}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}
{title: "New Event", selectPdf: "contract", panelContract: {…}, pdfTitle: "New Event"}`

So this is actually pretty odd since childPDFTitle isn't actually set. But I saw "title" is there, so changing it to `"calculateValue": "console.log(data);\nvalue = data.childPDFTitle;"` worked. 

Now on to the example app:
This is what I get in the console:
`{pdfTitle: "", childPDFTitle: "New Event"}
{pdfTitle: "New Event", childPDFTitle: "New Event"}
{pdfTitle: "New Event", childPDFTitle: "New Event"}
dab2b915-fc72-5144-a4cf-b9476e1a18bf.html?id=efzwnz:148 postmessage data invalid json:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _dispatch (dab2b915-fc72-5144-a4cf-b9476e1a18bf.html?id=efzwnz:148)
{pdfTitle: ""}
pdfTitle: ""}`

So the first time it logs, it actually appears pdfTitle will have the new value, but when it finally renders, it gets cleared out for some reason. I am not sure if the "invalid json" error we are seeing is causing an issue. But I also see that error when I use from the portal but it happens before any of my console logs.

I hope that is enough detail. All the help is much appreciated.

**Comment by wag110894** [comment]
Hello Austin, 

We do offer Support Packages to help you make the most of Form.io. Please send an email to support@form.io if you are interested in a Support package.

Thanks.

**Comment by austindbertola** [comment]
So should I consider this issue closed?

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
