### ISSUE TITLE
[BUG] Error in changing the display between 'form' and 'wizard'

### ISSUE THREAD

**Issue by chaosvibe** [formio/react#203]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

## Steps to Reproduce
1. Use FormEdit Component
2. change the display to 'wizard'
3. change the display back to 'form

## Expected behavior
The display of changes between 'form' and 'wizard'
## Observed behavior
The display of form doesn't change and when change back to 'form' there occurs an error
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
//Just simply use the FormEdit component
class CreateForm extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      form: {
        title: '',
        name: '',
        path: '',
        display: 'form',
        type: 'form',
        components: [],
      }
    }
  }
  
  onSubmit(form) {
    console.log(form)
  }

  render() {
    const { form } = this.state
    return (
      <FormEdit
        form={form}
        saveText='CREATE'
        saveForm={form => this.onSubmit(form)}/>
    )
  }
}

export {
  CreateForm
}
```

**Comment by randallknutson** [comment]
Recent builds had an issue with this the last couple days but the most recent version should be fixed. Can you test and verify that there is still an issue with the latest version?

**Comment by rchgonzaga** [comment]
> Recent builds had an issue with this the last couple days but the most recent version should be fixed. Can you test and verify that there is still an issue with the latest version?

Hi Randall, how are you ? when you say last versions, you mean 4.0.0-beta.16 ?

Thanks,
Rafael Gonzaga

**Comment by randallknutson** [comment]
Correct. We should be fixing this shortly.
