### ISSUE TITLE
[BUG] Unable to save component

### ISSUE THREAD

**Issue by aminmc** [formio/react#208]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.51
- Frontend framework: react-formio 4.0.0-beta.32
- Browser: chrome
- Browser version:

## Steps to Reproduce
1. Create new form using builder
2. Drag a component into canvas
3. Try to save component

## Expected behavior
Component should be saved to canvas
## Observed behavior
![Screenshot 2019-06-22 at 15 04 28](https://user-images.githubusercontent.com/290639/59964909-36e41780-94ff-11e9-836d-66f92305e730.png)

This seems to be an issue when upgrading react-formio.

**Comment by randallknutson** [comment]
I haven't experienced this yet. We'll be working on the 4.x branch again soon and if we see this we'll get it fixed.

**Comment by aminmc** [comment]
@randallknutson Any thoughts on this? I've tried latest versions of Formio and react and getting the same exception. I'm afraid we're blocked on this problem.

**Comment by randallknutson** [comment]
I'm still not able to replicate the issue. It might be a bad version of dragula or something as this appears to be in their code.

**Comment by aminmc** [comment]
Dragula is a dependency of formio js. I don’t see the version has changed. I’ll try to delete my package-lock and see if that makes a difference. There hasn’t been any change on the application side. I tried version .28 of react formio and that works.

**Comment by aminmc** [comment]
hi @randallknutson just tested formiojs .beta-54 and react version .29 and it works. After .29 i'm getting the above error.  Deleted package-lock file and started clean with my project. I can't imagine it's got anything to do with me using the semantic theme. Quite perplexing.  Just strange that it's only happening with i drag a component into the builder.

**Comment by aminmc** [comment]
@randallknutson After some digging around i found what is causing this problem:

```js FormBuilder.js
  componentWillReceiveProps = (nextProps) => {
    const {options, form} = this.props;

    if (
      (form.display !== nextProps.form.display)
      || (options !== nextProps.options)
      || (form.components !== nextProps.form.components) // removing this line fixes the issue
    ) {
      this.initializeBuilder(nextProps);
    }
  };
```
(form.components !== nextProps.form.components)  was added after .29 which has been breaking my application. I'm not raising a PR because I'm not sure why it was added.

**Comment by randallknutson** [comment]
I'll check with the developer who added that and see if there is a solution to this.

**Comment by aminmc** [comment]
Hi @randallknutson apologies for pestering on this issue but is there any updates? Can the change be reversed or is there something I can do on my side?

**Comment by aminmc** [comment]
@randallknutson can this change be reversed?

**Comment by aminmc** [comment]
Any updates on this? Happy to raise a PR to reverse this change but not sure why it was implemented in the first place.

**Comment by aminmc** [comment]
@randallknutson is this still an issue and you have done an rc release but I'm afraid I can't use it as mentioned before the above line breaks. Is this going to be resolved?

**Comment by aminmc** [comment]
@randallknutson Any updates on this?

**Comment by YuryRybakSoftensity** [comment]
We ere able to identify the issue and currently working on a fix.

**Comment by pixie79** [comment]
Hi,

Do we have an update on this?

Thanks

Mark

**Comment by randallknutson** [comment]
I believe Yury is still working on resolving the issue. It may be in the latest react-formio release already but I haven't had a chance to verify with him.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
