### ISSUE TITLE
[BUG] Remove babel-polyfill. It is depreciated and breaks other apps when your library is installed.

### ISSUE THREAD

**Issue by chadlavi-casebook** [formio/react#212]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.16
- Frontend framework: React
- Browser: n/a, compilation issue
- Browser version: n/a

## Steps to Reproduce
1. use react-formio in a storybook app with storybook version 5.1.9 or higher

## Expected behavior
App compiles

## Observed behavior
because of babel-polyfills, the app will crash.

**Comment by chadlavi-casebook** [comment]
see also https://github.com/storybookjs/storybook/issues/6204

**Comment by chadlavi-casebook** [comment]
This may also be related to #136

**Comment by randallknutson** [comment]
We do need to do this. If you want to create a pull request you can. Otherwise I'll do it for the next build.

**Comment by chadlavi-casebook** [comment]
Thanks for the quick reply Randall! 

I don't have the bandwidth to make the change, since I don't know how you're using it, so I imagine it would take some trial and error. I only figured out that this was the problem by tracking down error messages about why the new version of storybook wouldn't compile for the app my team uses to create high-fi mockups.

If it's predictable, when do you think the next build will be, roughly? Like, are we talking hours, days, months?

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
