### ISSUE TITLE
[bug] [dataloss] [interop] Editing a form may lose all components during save

### ISSUE THREAD

**Issue by franke-mc** [formio/react#214]
**Scenario 1:**
1. Create a form (not a wizard) with at least one component using an AngularJS version of the form builder (e.g. formio: 1.31.1, formiojs: 2.32.2)
2. ~~Observe that the form contains `"page": 0` in the POST to /form .~~
3. Edit that form with react-app-starterkit form editor (e.g. react-formio 3.1.12, formiojs: 3.22.15)
4. Observe that upon clicking "Save Form", all components are lost:
  The PUT to /form/... contains `"components": []` .

~~Removing the "page" attribute from the form before editing it appears to prevent this problem.~~

**Comment by franke-mc** [comment]
**Scenario 2:**
1. Create a form (not a wizard) with at least one component using an Angular version of the form builder (e.g. angular-formio: 3.16.2, formiojs: 3.21.5)
2. Edit a component with react-app-starterkit form editor, e.g. extend the Label text.
3. Observe that when saving the form, all components are lost, as above.

Apparently this happens even though the form does not have a "page" attribute in this case.

**Comment by franke-mc** [comment]
**Scenario 3:**
1. Create a form (not a wizard) with at least one component using react-app-starterkit form builder (e.g. react-formio: 3.1.12, formiojs: 3.22.15)
2. Click on "Edit Form"
3. In the Browser, click Shift-Reload.
4. Edit a component, e.g. extend the Label text.
5. Observe that when saving the form, all components are lost, as above.

Note that some variants of this scenario are blocked by issue #208.

**Comment by randallknutson** [comment]
I just reverted some issues that I introduced from an issue with the wizard and fixed them. Obviously your scenarios aren't with wizards but they may be related. I'll double check what is going on and see if these work for me today.

**Comment by franke-mc** [comment]
Helper script for setting up the test environment for scenario 3 above:
[formio-components-all-lost.sh.txt](https://github.com/formio/react-formio/files/3355683/formio-components-all-lost.sh.txt)

**Comment by franke-mc** [comment]
While keeping formiojs 3.22.15, I tried downgrading react-formio to 3.1.{11,9,7,6}, but the bug still occurs. With 3.1.5 and below I see either a JS error at runtime, or compile-time errors.

Next plan is to downgrade both react-formio and formiojs in sync to find a version without this bug.

**Comment by franke-mc** [comment]
@randallknutson: Did you find out anything already? Do you known of any combination of formio versions where this has worked robustly in the past? As the bug does not occur on current beta.form.io, maybe you can state some versions likely to be good?

**Comment by franke-mc** [comment]
This issue as described in scenario 3 does not occur with react-formio: 4.0.0-beta.34 and formiojs: 4.0.0-rc.4 (with CheckMatrix removed from src/components of react-app-starterkit 3fdd695313346727a5221d29301bfc7c7d2c7a0c ). The helper script is [here](https://github.com/formio/react-formio/files/3368992/formio-components-all-lost.sh.txt).

There are some JS warnings, though:
- Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

- Warning: Failed prop type: Invalid prop `columnWidths` of type `array` supplied to `_class`, expected `object`.

**Comment by franke-mc** [comment]
Other known-good versions combinations:
- react-formio: 4.0.0-beta.20, formiojs: 4.0.0-beta.38
- react-formio: 4.0.0-beta.6, formiojs: 4.0.0-beta.27

Maybe this problem never appeared on the 4.x branch?!

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
