### ISSUE TITLE
[BUG] Infinite loop detected when click next in wizard

### ISSUE THREAD

**Issue by giovanidalpiva** [formio/react#219]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:4.0.0-rc.1
- Frontend framework:4.0.0-rc.1
- Browser: Google Chrome
- Browser version:75.0.3770.100 (Official Build) (64-bit)

## Steps to Reproduce
1. create a new wizard
2. go to add a new item
3. in a step of the wizard click next

## Expected behavior
if the required fields are filled, to go to the next step of the wizard

## Observed behavior
the system get very slow, and when you open the console, you can see a lot of messages of infinite loop detected, and the number of messages increase after some time, and the next step of the wizard never comes

## Example
![Screen Shot 2019-07-04 at 10 50 47 PM](https://user-images.githubusercontent.com/2424751/60693149-7e7b8380-9eaf-11e9-9e09-baa91a38d497.png)

**Comment by randallknutson** [comment]
This may be fixed in the latest rc. Can you test it with the newest version? If not we may need an example form to check on.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
