### ISSUE TITLE
Creating FormIO custom component to use HandsOnTable spread sheet in form builder using React JS

### ISSUE THREAD

**Issue by tmohanbtech** [formio/react#250]
Hi,
I am new to Form IO and need to create a custom component using HandsOnTable Spreadsheet which will be available in my form builder , so that user can able to use Spredsheet in the forms. It could be better some one can help me to create new component as Spreadsheet using HandsOnTable and integrate in Form IO builder using React js. Thanks

**Comment by aiwebb** [comment]
@tmohanbtech, here is an example of a custom component in React: https://github.com/formio/react-app-starterkit/tree/3.x/src/components

**Comment by tmohanbtech** [comment]
Thanks for your answer @aiwebb. I have gone through the above link but I need to construct new custom component using third party element i.e HandsOnTable Spreadsheet. Is there any way that we can directly render another third party component in FormIO components

**Comment by aiwebb** [comment]
@tmohanbtech, you can set `this.element` in your `build()` function to a dynamically created element that is then wrapped by HandsOnTable as a new table instance.

**Comment by simonv3** [comment]
The example in the react-app-starterkit is pretty old - using formio 3.x - is there nothing newer? 

For example, the line that supposedly loads the components:

```
import { initAuth, Formio, Components } from 'react-formio';
```

none of those objects are still existing in react-formio? It does look like now there's a `ReactComponent` function that might be useful, but without any documentation :shrug:
