### ISSUE TITLE
[BUG] S3 integration with Embedded Form

### ISSUE THREAD

**Issue by KalebMatthews** [formio/react#251]
## Environment
Please provide as many details as you can:

- Hosting type:
  - [x] Form.io
- Formio.js version: currently: v4.1.1
  - Using: https://unpkg.com/formiojs@latest/dist/formio.full.min.js
- Frontend framework: Raw HTML/CSS/JS using React Project in interface.
- Browser: Chrome & Firefox
- Browser version: 
  - Chrome: 76.0.3809.132
  - Firefox: 69.0.1 (64-bit)

## Steps to Reproduce
1. Create a form with a purely public S3 bucket to store data
2. Verify the upload file works via the use tab in the web interface
3. Embed the form on the webpage using the script embed method
4. Attempt to upload a file. "Invalid Alias" error will appear.

## Expected behavior
If it works in the use tab it should work if it is embedded.

## Observed behavior
Works inside the formio ecosystem but not when it is embedded in our system.

## Example

From Embedded Code:
<img width="1527" alt="FromEmbed" src="https://user-images.githubusercontent.com/29708600/65343825-fd758380-dba3-11e9-994a-a16764c3daf1.png">

From Formio Interface:
<img width="1680" alt="FromFormioInterface" src="https://user-images.githubusercontent.com/29708600/65343826-fd758380-dba3-11e9-9307-db9fd072eb4f.png">

Code Snippet:

```js
<link rel="stylesheet" type="text/css" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
<script type="text/javascript" src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>

...
<script>
Formio.createForm(document.getElementById('formio2'), [Formio Form URL])
  .then(function(form) {
    // What to do when the submit begins.
    form.on('submitDone', function(submission) {
      window.location = '/thanks';
    });
  });
</script>
...
```

**Comment by travist** [comment]
Thanks for the detailed bug report. We will take a look.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
