### ISSUE TITLE
[BUG] Can't find expected format for adress field component default value

### ISSUE THREAD

**Issue by Rvaucher** [formio/react#254]
Hi,

Despite looking for it in the documentation, I can't find the expected format for the address component default value.

Could you please tell me what is expected ?

Thanks in advance,

Best regards.

**Comment by randallknutson** [comment]
This is a tricky one. Currently it is using the response from google api address lookup as the data type. I believe it follows some sort of an international standard for addresses. 

We are planning on updating the address component to allow other providers and to standardize the format to the international standard.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
