### ISSUE TITLE
[Question] perms functionality for hiding/showing buttons submissionGrid? 

### ISSUE THREAD

**Issue by theonebigblue** [formio/react#268]
Is it possible to get the perms functionality from formGrid for hiding/showing submissionGrid?

**Comment by randallknutson** [comment]
I don't think this was ever fully finished. The idea was that each submission could have different permissions based on the user so there is a function that is passed in to evaluate what the permissions are for that user for that submission. I don't think we have fully finished code for that but it should be straightforward to write.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
