### ISSUE TITLE
[BUG] Changing page in submissiongrid does not render new submissions

### ISSUE THREAD

**Issue by theonebigblue** [formio/react#269]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 1.58.0
- Formio.js version: 4.7.4
- Frontend framework: react-formio 4.2.3
- Browser: Chrome
- Browser version:  78.0.3904.97

## Steps to Reproduce
1.  Use react-app-starterkit as base
2.  connect to api server
3.  In api server add event as resource and add +10 submissions

## Expected behavior
When loding the example with submisson grid and changing page it is expected that it sould render new submissions.
## Observed behavior
It allways renders the 10 first submissions, even if start page is set to >1 in code.

## Example
Se example code in react-app-starterkit

**Comment by randallknutson** [comment]
We've a lot of apps using this code and they haven't reported this issue before. Can you check if the limit and skip are being sent to the server correctly?

**Comment by theonebigblue** [comment]
It does not seem to pass them correctly, i get _submission?limit=undefined_ and submission?limit=undefined&skip=NaN.

Can't seem to find where i should set the limit.

**Comment by theonebigblue** [comment]
I  can make the pagnation (i.e the skip) to work if i hard code a limit in submissions/actions.js

**Comment by jhen1422** [comment]
@theonebigblue Thank you for the report. We have added this issue to our React issue backlog and will notify you when this has been resolved. We will review during our planning meeting next week. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
