### ISSUE TITLE
[BUG] React-formio: getForm Action is not working when try to fetch form details by alias.

### ISSUE THREAD

**Issue by hanumanthraju** [formio/react#280]
## Environment
Please provide as many details as you can:

- react-formio: ^4.0.0-rc.11
- Formio.js version: ^4.0.0-rc.21

## Steps to Reproduce
Try to fetch form details by form alias or name.

## Expected behavior
Fetch a form from the server. If no id is provided, the name is used as the path
## Observed behavior
TypeError: Cannot read property '1' of null

## Example

<img width="704" alt="Screenshot 2019-12-24 at 7 48 26 PM" src="https://user-images.githubusercontent.com/6049341/71416800-27997e80-2688-11ea-85ce-313f2e2c8e3e.png">
<img width="735" alt="Screenshot 2019-12-24 at 8 00 55 PM" src="https://user-images.githubusercontent.com/6049341/71416814-341dd700-2688-11ea-9dcb-e19c797c8f51.png">
<img width="739" alt="Screenshot 2019-12-24 at 8 01 05 PM" src="https://user-images.githubusercontent.com/6049341/71416815-341dd700-2688-11ea-89f0-10ac031f7f51.png">
React Reducer sample code

```js
 event: combineReducers({
    form: form({ name: 'event'}),
    submission: submission({name: 'event'}),
    submissions: submissions({name: 'event'}),
  })

const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    getForm: () => dispatch(getForm('event')),
    onSubmit: (submission) => {
      dispatch(saveSubmission('event', submission, null, (err, submission) => {
        if (!err) {
          dispatch(resetSubmissions('event'));
          dispatch(push(`/event`))
        }
      }));
    }
  }
}
```
I think issue is because  of missing a forward slash in Ternary Operation on line 81 in Action.js file of form module.
<img width="1264" alt="Screenshot 2019-12-24 at 8 10 23 PM" src="https://user-images.githubusercontent.com/6049341/71417084-7d225b00-2689-11ea-8532-a3e0a7ac8277.png">

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
