### ISSUE TITLE
[Question] Is formio.full.min.js required?

### ISSUE THREAD

**Issue by elliott-w** [formio/react#311]
Do I need formio.full.min.js for react-formio? A lot of components seem to work fine without it, so is it the case that react-formio has a built-in npm dependency on that package?

**Comment by randallknutson** [comment]
You do not need formio.full.min.js for react-formio. If you are using a module bundler, formio.js will be bundled with it automatically. You may need to either include formio.css or at least the CSS for choices.js and flatpickr or those components will render unstyled and look funny.

**Comment by Eltyo** [comment]
Ah okay, sweet. Any chance I could get some links to the `<link>` tags required for choices.js and flatpickr just in case I need it for one of the components? 

Thank you!

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
