### ISSUE TITLE
[BUG] Conditionally displaying EditGrid data disappears

### ISSUE THREAD

**Issue by elliott-w** [formio/react#318]
1. Create a form that conditionally displays an Edit Grid component containing any sub-components
2. Create a submission of that form where the Edit Grid is displayed
3. Render that submission with react-formio
4. Edit one of the rows of the Edit Grid component -> **All fields are blank**
5. Press cancel
6. Edit the same row again -> All fields are now filled in

## Environment
- Hosting: Form.io
- Frontend framework: react-formio v4.3.0
- Browser: Chrome
- Browser version: v83.0.4103.116

**Comment by wag110894** [comment]
Hello Eltyo,

Thank you for reaching out! We are not able to replicate this issue on our Production portal. Can you please provide a JSfiddle of this issue taking place? 

Thank you.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
