### ISSUE TITLE
costum component data

### ISSUE THREAD

**Issue by hangover7** [formio/react#322]
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: react-formio 4.3.0
- Frontend framework: reactjs 16.13.1
- Browser:
- Browser version:

## Steps to Reproduce
I am new to Form IO and using https://codesandbox.io/s/81qb6 to create Toggle custom component .
but when submit my form toggle component not in submitted data. 
all default component is in submitted . 

![Screenshot from 2020-07-19 14-40-13](https://user-images.githubusercontent.com/68499045/87872451-0276af80-c9ce-11ea-8913-a197286f287b.png)

![Screenshot from 2020-07-19 14-40-36](https://user-images.githubusercontent.com/68499045/87872471-19b59d00-c9ce-11ea-9b49-05bef73a1441.png)

**Comment by wag110894** [comment]
@hangover7 Thank you for reaching out! Form.io offers Support Packages that are for training, support, or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. 

Please let us know if you are interested.

**Comment by darshanksexathought** [comment]
@hangover7 can you send the code on how did you implement the custom component?

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
