### ISSUE TITLE
Is it possible to use custom API url for nested form component call?

### ISSUE THREAD

**Issue by StephSince93** [formio/react#326]
I am wanting to redirect to my API with different params, but I haven't had any luck. I'm not sure if this is something that can be done.

I found the Formio.setBaseUrl and Formio.setProjectUrl functions, but that is just for the domain name.

**Comment by randallknutson** [comment]
What you can do is disable the default submission events by setting the url={formUrl} instead of src={formUrl}. Then listen for the onSubmit event and send the data wherever you would like.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!
