### ISSUE TITLE
Displaying confirmation message before deleting a component from FormBuilder

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/react#334]
Hi!
I was trying to implement a confirmation dialog before user tries to delete any component from the FormIO FormBuilder:
![image](https://user-images.githubusercontent.com/49182064/93569103-0486cb80-f989-11ea-9c25-ce12ec882148.png)

I found that there's a `onDeleteComponent` event for `FormBuilder`, but it seems to be triggered **after** the component has actually been deleted from the form. Returning true/false from this function changes nothing.

I know there's a confirmation message when trying to delete a group (e.g. columns layout) with nested items (the message says "Removing this component will also remove all of its children. Are you sure you want to do this?'"). I'd like to do the same, but for all components in the builder, not only grouped ones.

Is there any way to handle this currently or a PR would be needed?

**Comment by randallknutson** [comment]
I believe a PR would be needed. The onDeleteComponent is an event so it notifies you of that happening but does not allow modification of the flow. If you set up a PR with this change, it would probably be best to make it an option that can be passed in so that we don't change the default functionality.

**Comment by randallknutson** [comment]
If you haven't found it, the code is here: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L960-L970

**Comment by mm-dsibinski** [comment]
I issued a PR with this change: https://github.com/formio/formio.js/pull/3396
