### ISSUE TITLE
[BUG] Wizard Null-components сauses an error

### ISSUE THREAD

**Issue by vaspaul** [formio/react#344]
## Environment
- React-formio version: "^4.2.4"
- Formio.js version: "4.11.0"
- Frontend framework: React "^16.8.6"
- Browser: many browsers.
- Browser version: many browser versions.

## Steps to Reproduce
1. The user edit a Wizard form (in Wizard-Builder) and delete the "Panel" component.
2. When the user delete this component, there is a substitution of the "Panel" form component to "null" (in "components" array).
3. The user saves the JSON-schema of the wizard with these "null-components".
4. The user calls this form to enter values using the "Form" react-component. A null-related error occurs due to stored "null-components".

## Expected behavior
- It is expected that when deleting a component of the "Panel" form, the component is completely removed from the array, but not only replaced with "null". The error is not expected to occur.

## Observed behavior
- An error occurs when trying to pass the wizard json schema with null components to the "Form" React component.

## Example
Some code with "Form" component:
```js
...
import { Form, Formio } from 'react-formio';
...
render() {
    ...
    <Form
        form={there_is_my_var_with_wizard_schema_contains_null-conponents}
        ...
    />
    ...
}
...
```
Error from browser console:
> Uncaught TypeError: item is null
    setComponentSchema Wizard.js:943
    setComponentSchema Wizard.js:942
    setForm            Wizard.js:972
    set                Webform.js:1993
    set                Wizard.js:259
    _set               Wizard.js:263
    set                Wizard.js:1116
    setForm            Form.js:394
    Form               Form.js:283
    componentDidMount  Form.js:172

Wizard with null-components:
![Wizard with null-components](https://user-images.githubusercontent.com/46297009/96963640-a1510180-1511-11eb-9318-564f528716a0.jpg)

**Comment by alexandraRamanenka** [comment]
Surely, it's a bug. Normally, when user deletes a component it should be completely removed from components array. There were a lot of changes done to Wizard component recently, so it seems that it is a bug in the core renderer. We will add it to our planning.

**Comment by wag110894** [comment]
@vaspaul, For reference, the ticket number is FJS-1370. It is currently on our backlog. We will let you know once this issue has been resolved.

**Comment by jhen1422** [comment]
Our dev team was unable to reproduce the issue. 

Please retest this using latest FJS and React versions
