### ISSUE TITLE
[BUG / UNEXPECTED BEHAVIOR] The error-message does not reflect the cause of the error.

### ISSUE THREAD

**Issue by vaspaul** [formio/react#346]
## Environment
- React-formio version: "^4.2.4"
- Formio.js version: "4.11.0"
- Frontend framework: React "^16.8.6"
- Browser: many browsers.
- Browser version: many browser versions.

## Steps to Reproduce
0. Create a form, add the "Text Field" component to it. (The edit window opens immediately after that)
1. Enter non-Latin characters in the "Label" field.
2. Try to save.
3. Pay attention - An area with an error description appears

## Expected behavior
It is expected that the user to be notified that non-Latin characters are not allowed.
I have some suggestions:
1. Add an additional notification to the user that non-Latin characters are forbidden in the "Properties Name" field of the "API" tab.
2. Disable the ability to automatically fill in the "Property Name" field of the "API" tab when filling in the "Label" field of the "Diaplay" tab.

## Observed behavior
Error message:
>Please fix the following errors before submitting.
>Property Name: The property name must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.

## Example:
![pic1](https://user-images.githubusercontent.com/46297009/97415780-ae596080-1916-11eb-8b17-55066821c09f.png)
![pic2](https://user-images.githubusercontent.com/46297009/97415784-af8a8d80-1916-11eb-90aa-fe7ad66cae0e.png)
![pic3](https://user-images.githubusercontent.com/46297009/97415791-b0232400-1916-11eb-8fc1-fbb429b0b51b.png)
![pic4](https://user-images.githubusercontent.com/46297009/97415793-b0232400-1916-11eb-9180-949e36b588c7.png)
![pic5](https://user-images.githubusercontent.com/46297009/97415796-b0bbba80-1916-11eb-9af9-4b4648b0592f.png)

**Comment by wag110894** [comment]
Hello @vaspaul,

Thanks for reaching out! This error means that the API that you have added to the API key section is not valid, so you will need to change it. You can change the Label back after the initial save and it will not impact the API key.

I hope that this helps.

**Comment by vaspaul** [comment]
Hi, @wag110894 ,
Will developers add this information to the error message explicitly in the next release?
