### ISSUE TITLE
[BUG] formReady event not firing

### ISSUE THREAD

**Issue by adventmedia** [formio/react#354]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.3.0
- Formio.js version: 4.12.1
- Frontend framework: React 16.13.1
- Browser: Chrome 
- Browser version: 87.x

## Steps to Reproduce
```
        <Form
          form={definition}
          options={{ readOnly: false }}
          onCustomEvent={customEvent}
          formReady={(e: any) => console.log('form: ready', e)}
        />
```

## Expected behavior
formReady event fires when form is loaded

## Observed behavior
nada. nothing. (customEvent works as expected)

**Comment by travist** [comment]
Thanks for the bug report. We will take a look.

**Comment by wag110894** [comment]
Hello @adventmedia,

We have created a ticket and have added this to our backlog. We welcome a pull request or have a process to expedite this issue if you are interested. For reference, the ticket number is FIO-187.

**Comment by SalTor** [comment]
@wag110894 Any update on this ticket FIO-187?

**Comment by wag110894** [comment]
Hello @SalTor,

This item is still in our backlog. As mentioned above, we do welcome a pull request or have a process to expedite this issue if you are interested.
