### ISSUE TITLE
[BUG] Typing spaces to Text Area does not trigger an onChange

### ISSUE THREAD

**Issue by christianztamayo** [formio/react#360]
## Environment
- Hosting type: Local deployment
- React Formio.js version: 4.3.0

## Steps to Reproduce
1. Go to [codesandbox example](https://codesandbox.io/s/react-formio-textarea-onchange-w5we5?file=/src/App.js)
2. Type in spaces to the Text Field
3. Bottom log should print `[timestamp]: textField changed`
4. Now type in spaces to the Text Area
5. Bottom log does not print anything since `onChange` is not being triggered

## Expected behavior
Typing spaces to a text area component should trigger the Form's `onChange`

## Observed behavior
Typing spaces to Text Area does not trigger the Form's `onChange`

## Example
https://codesandbox.io/s/react-formio-textarea-onchange-w5we5?file=/src/App.js

**Comment by wag110894** [comment]
Hello @christianztamayo, Can you confirm that the version you are referencing is the React version and not the formio.js version?

**Comment by namti** [comment]
I found the same issue
```json
"react-formio": "^4.3.0"
```

**Comment by namti** [comment]
Just tried [5.0.0-rc2](https://www.npmjs.com/package/react-formio/v/5.0.0-rc.2). It is fixed in this version
