### ISSUE TITLE
Extending a existing component

### ISSUE THREAD

**Issue by Anandks1993** [formio/react#367]
Hi, I have one requirement to override the existing `Signature` component. In which I need to show one Checkbox along with Signature component. Only if the Checkbox is ticked and Signature is drawn the field should be considered as a valid one in Form Renderer.

**Comment by travist** [comment]
This shows how to extend a component.

https://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by Anandks1993** [comment]
Thank you, I will check.

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!
