### ISSUE TITLE
Example of PDF FormBuilder

### ISSUE THREAD

**Issue by Anandks1993** [formio/react#371]
Hi, 

I am going to tryout the PDF FormBuilder mode and right now when I try to upload a PDF it uses `https://api.form.io/upload` API to upload the file. Is there a way to modify this like `FileService` for `file component`? 

**Note:** I tried setting `projectUrl` in the options but it appends the `/upload` text at the back in the API, also need to add headers for authentication.

Thank you for this wonderful package and thank you in advance.

**Comment by travist** [comment]
You can modify where this goes by altering the following code.

https://github.com/formio/formio.js/blob/master/src/PDFBuilder.js#L221

You can then just send this file whereever you want.

```js
// This is how you override the upload method in the pdf builder.
Formio.Builders.builders.pdf.prototype.upload = function(file) {

};
```

**Comment by Anandks1993** [comment]
@travist Thank you very much for quick response. I will check out this.

**Comment by Anandks1993** [comment]
Hi @travist as you suggested I could upload PDF to custom server and convert it to HTML like `formio` does. But when I try to render the generated html document the components inside the sidebar is disabled, I could not drag and drop over the html pdf file. Am I missing something here which makes the buttons to go disabled?

Thank you in advance.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
