### ISSUE TITLE
render the form form FormGrid using react form.io

### ISSUE THREAD

**Issue by rahulseth625** [formio/react#377]
Formio.js version: "^4.0.0-rc.21",
Frontend framework: "react": "16.8.2",
Browser: chrome
Browser version: Version 88.0.4324.104 (Official Build) (64-bit)

## Steps to Reproduce
1. Want to render the form using FormGrid

## 
![page](https://user-images.githubusercontent.com/33866915/107774885-9c84b780-6d65-11eb-8c99-904d9480ce2f.png)

```js
import React, { useState, useEffect } from 'react';
import { indexForms, selectRoot, selectError, Errors, FormGrid } from 'react-formio';
import axios from 'axios';

const Grid = (props) => {

  const [getFormList, setForm] = useState([]);

  const getFormLists = () => {

    axios.get('http://localhost/db_react_protrack/user-data/user-data-select.php').then(response => {
      setForm({ forms: response.data })
    })
      .catch(err => {
        console.log(err)
      })

    const { forms } = getFormList;

    return <div>
      {getFormList.length === 0 ?
        null
        : <FormGrid forms={forms}
        />
      }
    </div>
  }

  useEffect(() => {
    getFormLists();
  }, []);

  return (
    <div>
      <span>
        {getFormLists()}
      </span>
    </div>
  )
}
export default Grid
```
Kindly please help me.
Thanks in advance.

**Comment by wag110894** [comment]
Hello @rahulseth625, can you upgrade the formio.js that you are using? The project JSON mentions that the formio.js version must be at least 4.12.4-rc.2.

**Comment by rahulseth625** [comment]
@wag110894  I am using "formiojs": "^4.12.7". But still getting the same error. Kindly pls help

**Comment by alexandraRamanenka** [comment]
@rahulseth625 that is because FormGrid expects **forms** property to be an **object** with the following properties:
```
  { 
      forms,
      limit,
      pagination: {
        page,
        numPages,
        total,
      },
      sort
   }
```
I know that it may be a bit confusing and unexpected, but this is because it was built first for using with Redux and forms property was representing the full state controlled by forms reducer.

**Comment by rahulseth625** [comment]
@alexandraRamanenka @wag110894 
How to upgrade the formio.js version. Pls share the command. I am using redux react-app-starterkit.
