### ISSUE TITLE
[Question] FormBuilder GET API

### ISSUE THREAD

**Issue by fdurna** [formio/react#383]
Hello Guys, 
Im using FormBuilder , How to load form/json data previously saved?
@randallknutson 

![image](https://user-images.githubusercontent.com/15355851/111024990-a34d2b80-83f2-11eb-806e-06c9d873f0d7.png)

![image](https://user-images.githubusercontent.com/15355851/111025010-bb24af80-83f2-11eb-9ac6-0fec54fb967f.png)

![image](https://user-images.githubusercontent.com/15355851/111025019-cd9ee900-83f2-11eb-9e3c-97ddad47f340.png)

**Comment by alexandraRamanenka** [comment]
You should put the whole form schema JSON (like the one which you get on your first screen) to the builder's **form** property.
