### ISSUE TITLE
[Question] Create new element with different options

### ISSUE THREAD

**Issue by fdurna** [formio/react#384]
hello guys I hope you are doing well ,

I wanna add new radio btn element under basic element something similar to  Radio element with small difference in options like under data tab 10 labels gonna come as default not one  and change the some other option 

![image](https://user-images.githubusercontent.com/15355851/111972749-d7210300-8b0e-11eb-9bab-3f193d8a2380.png)

![image](https://user-images.githubusercontent.com/15355851/111973180-48f94c80-8b0f-11eb-862a-4476d1caf8b9.png)

thank you...

**Comment by wag110894** [comment]
Hello @fdurna, You can accomplish this using the custom builder.
https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by fdurna** [comment]
> Hello @fdurna, You can accomplish this using the custom builder.
> https://formio.github.io/formio.js/app/examples/custombuilder.html

I created a new one, but I want 10 from Values to come ready
