### ISSUE TITLE
[QUESTION]  Failed prop type: Invalid prop `form`

### ISSUE THREAD

**Issue by fdurna** [formio/react#388]
How can i do  fix ? form prop i get this error , 

![image](https://user-images.githubusercontent.com/15355851/112739690-ef65a780-8f7e-11eb-80f0-1e44b65a0fb1.png)
![image](https://user-images.githubusercontent.com/15355851/112739710-3784ca00-8f7f-11eb-8cda-73fb2371c9cc.png)

**Comment by travist** [comment]
The ```form``` object should not be an array, so not sure why it is saying that it is expected, but it would help to know what the value of your "form" is here. Is it an object or an array?

**Comment by fdurna** [comment]
I write the data to the console, you can find it in the appendix @travist 
![image](https://user-images.githubusercontent.com/15355851/113762470-4870d080-9721-11eb-96c9-d2027752ac85.png)
Thank You.

**Comment by fdurna** [comment]
Why are you closing the ticket? I did not get the answer. @wag110894

**Comment by alexandraRamanenka** [comment]
@fdurna you set **form** to **items** state. And initial value of **items** is [], that's why it fails. Set initial value to something like this
```
const [items, setItems] = useState({ display: 'form', components: [] });
```

**Comment by fdurna** [comment]
thank you very much, it worked @alexandraRamanenka
