### ISSUE TITLE
[BUG] Component's side menu section can't be expanded after search

### ISSUE THREAD

**Issue by eros-piccioni** [formio/react#391]
## Environment
- react-formio version: 4.3.0
- Formio.js version: 4.13.1
- Frontend framework: React
- Browser: Google Chrome
- Browser version:  90.0.4430.93 (Official Build) (64-bit)

## Steps to Reproduce
1. I'm using the example project https://github.com/formio/react-app-starterkit to test the Form Builder as is;
2. Edit a form of the example project;
3. Search components in the component's side menu, clear the search filed with x icon click or text cancel.

## Expected behavior
After searching and clearing the search field  I expect to be able to expand and access the different sections of the component's side menu.

## Observed behavior
After searching and clearing the search field a click on the closed section won't open them. I observe the same bug in a react project with the same environment.

## Example
Here a short GIF as example on what I experience.

![Form Builder Side Menu](https://user-images.githubusercontent.com/40391627/117625426-4b267180-b176-11eb-86bd-f96ed8df5562.gif)

I hope I provided enough details. Any help would me much appreciated, thanks!

**Comment by wag110894** [comment]
Hello @ErosII, Can you still replicate this on latest verison of Form.io React and Formio.js?

**Comment by ErosII** [comment]
I can still replicate with `formiojs` 4.13.2 (latest stable) and `@react/formio` 5.0.0. Is it safe to use also the release candidates for example the lastest 4.14.0-rc.12? Should i give it a try?

**Comment by SanleyPan** [comment]
Same issue

**Comment by Anandks1993** [comment]
Same issue

formiojs: 4.13.9
@formio/react: 5.1.1

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
