### ISSUE TITLE
[BUG] The data grid component doesn't save submission data of the first row

### ISSUE THREAD

**Issue by namti** [formio/react#392]
## Environment
Please provide as many details as you can:

- Hosting type
  - [    ] Form.io
  - [ x ] Local deployment
    - Version: 
- Formio.js version: 4.3.0
- Frontend framework: ReactJS
- Browser: Chrome
- Browser version: Version 89.0.4389.114 (Official Build) (x86_64)

## Steps to Reproduce <a href="#steps-to-reproduce" id="steps-to-reproduce">#</a>
1. On the form builder, create a data grid component, add components to the row.

2. Go to form view, fill in data for the first row and add more rows.    
![image](https://user-images.githubusercontent.com/2180936/118417716-7c201c80-b709-11eb-95d9-5116b061db8f.png)

3. Check the data json in react dev tool, the first item is an empty array which should not be.
![image](https://user-images.githubusercontent.com/2180936/118070787-a9fc1d00-b3fa-11eb-999f-66e9fbb121fc.png)

## Expected behavior
Save all data

## Observed behavior

At the moment, this problem only can be fixed by editing the component on the form builder manually (not by code). 
Here is the steps to reproduce:
1. Edit a form
2. Add a data grid component
3. Edit it
4. Switch to "Data" tab
5. Click on "Add another" to add one
6. Remove the first one. Save it
7. Fill in data on the form view. Check the react dev toll, data appeared.
![image](https://user-images.githubusercontent.com/2180936/118071786-8df97b00-b3fc-11eb-8e4e-0b0f40de8faa.png)

**Comment by HCMF** [comment]
I have this bug to... here is a video of the issue: [ https://youtu.be/tkCQCksowk4](url)

**Comment by wag110894** [comment]
@namti 
@HCMF 

What versions of formio.js are you running on?

**Comment by HCMF** [comment]
I am also using 4.3.0

**Comment by wag110894** [comment]
This formio.js is rather old. Can you try upgrading? The latest stable version is 4.13.1.

**Comment by HCMF** [comment]
As this is the React version, is it possible to update just the core formio.js?

**Comment by namti** [comment]
I have spotted the bug. 

The first row which is generated by default always returns an array with object keys and values in it. 
![image](https://user-images.githubusercontent.com/2180936/118573636-100bea00-b7d7-11eb-9f67-3c0960e90f2b.png)
When setState in react, the illegal array is ignored and it is fell back to an empty array.

I have tried to upgrade to [5.0.0-rc.2](https://www.npmjs.com/package/react-formio/v/5.0.0-rc.2), unfortunately the bug is still there.

**Comment by wag110894** [comment]
@namti, We welcome a pull request if you can provide a fix for the issue, then we can pull it in.

**Comment by AlpineM** [comment]
I am also having trouble with this bug. Was it ever resolved?

**Comment by daneformio** [comment]
We are not able to reproduce this in the latest versions. Are you still having this issue in the latest versions?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
