### ISSUE TITLE
[BUG] Form's onChange not called after form's field validation rule updated from required to non-required

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/react#411]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    - Version: N/A, issue only with @formio/react
- Formio.js version: 4.13.7
- @formio/react version: 5.1.1
- Frontend framework: React
- Browser: Google Chrome
- Browser version: Version 94.0.4606.71 (Official Build) (64-bit)

## Steps to Reproduce
I prepared a simple app reproducing the problem:

[formio-validation.zip](https://github.com/formio/react/files/7302003/formio-validation.zip)

Unzip the app and launch it by executing `npm install` first and then `npm start` inside the app folder.

The app simply renders a Form with some form definition object provided with `form` property and logs the fact that `onChange` was called in the console:

```javascript
const onFormChange = (submission) => {
    console.log("onFormChange called");
  };
.....
<Form form={formObject} onChange={onFormChange} />
```

Initially, the multi-choice component is set as required in the form definition's validation section (`formWithRequired` object):

![image](https://user-images.githubusercontent.com/49182064/136370508-a25d2e8a-8d21-4e2c-bd5e-1293cc59b783.png)

When the app opens in the browser, open Developer Console.

When checking and unchecking the checkboxes, you can see in the console that `onChange` is called properly after each change:

![image](https://user-images.githubusercontent.com/49182064/136370233-be9529cf-f331-4b38-a9c2-2b7cf2989a28.png)

Now, click the "Set not required" button:

![image](https://user-images.githubusercontent.com/49182064/136370296-cb0a1a2a-0aed-4a2c-8736-09bb3fd43c09.png)

It basically calls the function which sets new `form`. The only difference is that in this new form's definition (`formWithoutRequired` object) the required is set to `false`:

![image](https://user-images.githubusercontent.com/49182064/136370596-88e7e84d-e60e-4f79-bad8-7aaae0fdfeb2.png)

After clicking this button, you can see in the console **that the `onChange` event is not called anymore**.

## Expected behavior
The `onChange` event should always be called. Even if the state of the form has been changed with different validation rules.

## Observed behavior
The `onChange` event is not called as soon as the `form` property of `Form` component is changed to another one with non-required validation rules.

## Additional info
What is even stranger, is that when you click "Set required" button again, the `onChange` will be called properly again.
Additionally, **it works correctly with @formio/react 5.0.0.**

I think it may be related to these changes: https://github.com/formio/react/commit/7b67970fd7e56e96d0f23dd699d263943ab6488f
But I'm not sure about that.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
