### ISSUE TITLE
Multiple forms with submit buttons on one page 

### ISSUE THREAD

**Issue by LenaKis** [formio/react#418]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
Hello! I use formiojs v4.12.1-rc.16. I have two forms

First form
{"components":[{"label":"Текстовое поле","tableView":true,"key":"textfield","type":"textfield","keyModified":true,"input":true},{"label":"Кнопка","showValidations":false,"tableView":false,"key":"submit1","type":"button","keyModified":true,"input":true}]}

Second form
{"components":[{"label":"Текстовое поле","tableView":true,"key":"textfield","type":"textfield","keyModified":true,"input":true},{"label":"Кнопка","showValidations":false,"tableView":false,"key":"submit2","type":"button","keyModified":true,"input":true}]}

If I submit first form, then second form was submitted too.

How can I split the two forms?
```

**Comment by LenaKis** [comment]
Hello! I use formiojs v4.12.1-rc.16. I have two forms 

First form
{"components":[{"label":"Текстовое поле","tableView":true,"key":"textfield","type":"textfield","keyModified":true,"input":true},{"label":"Кнопка","showValidations":false,"tableView":false,"key":"submit1","type":"button","keyModified":true,"input":true}]}

Second form
{"components":[{"label":"Текстовое поле","tableView":true,"key":"textfield","type":"textfield","keyModified":true,"input":true},{"label":"Кнопка","showValidations":false,"tableView":false,"key":"submit2","type":"button","keyModified":true,"input":true}]}

If I submit first form, then second form was submitted too.

How can I split the two forms?

**Comment by AlexeyDavyd** [comment]
@LenaKis Could you please share an example of how do you exactly rendering these two forms?

**Comment by LenaKis** [comment]
let form1 = '{"components": [{"label": "Текстовое поле", "tableView": true, «key»: «textfield», «type»: «textfield», «keyModified»: true, «input»: true}, {"label": "Кнопка", "showValidations": false, "tableView": false, "key": "submit1", "type": "button", "keyModified": true, "input": правда}]}';

let formElem= document.getElementsByClassName('formio-content')[0];

var dataComponents = [
    {
        type: 'datagrid',
        key: 'values',
        components: [
            {
                type: 'select',
                key: 'shortcut',
                tooltip: 'Сочетание клавиш для этой опции.',
            }]

    }
];

var logicComponents = [
    {
        key: 'logic',
        input: true,
        templates: {
            header: '<div class="row"> \n  <div class="col-sm-6">\n    <strong>{{ value.length }} sdfsdf</strong>\n  </div>\n</div>',
            row: '<div class="row"> \n  <div class="col-sm-6">\n    <div>{{ row.name }} </div>\n  </div>\n  <div class="col-sm-2"> \n    <div class="btn-group pull-right"> \n      <div class="btn btn-default editRow">Править</div> \n      <div class="btn btn-danger removeRow">Удалить</div> \n    </div> \n  </div> \n</div>',
            footer: '',
        },
        type: 'editgrid',
        components:
            [
                {
                    key: 'actions',
                    templates: {
                        header: '<div class="row"> \n  <div class="col-sm-6"><strong>действий {{ value.length }}</strong></div>\n</div>',
                        row: '<div class="row"> \n  <div class="col-sm-6">\n    <div>{{ row.name }} </div>\n  </div>\n  <div class="col-sm-2"> \n    <div class="btn-group pull-right"> \n      <div class="btn btn-default editRow">Править</div> \n      <div class="btn btn-danger removeRow">Удалить</div> \n    </div> \n  </div> \n</div>',
                        footer: '',
                    },
                    type: 'editgrid',
                }
            ]
    }];

const ru = {
    weekdays: {
        shorthand: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
        longhand: [
            "Воскресенье",
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота",
        ],
    },
    months: {
        shorthand: [
            "Янв",
            "Фев",
            "Март",
            "Апр",
            "Май",
            "Июнь",
            "Июль",
            "Авг",
            "Сен",
            "Окт",
            "Ноя",
            "Дек",
        ],
        longhand: [
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь",
        ],
    },
    firstDayOfWeek: 1,
    ordinal: function () {
        return "";
    },
    rangeSeparator: " — ",
    weekAbbreviation: "Нед.",
    scrollTitle: "Прокрутите для увеличения",
    toggleTitle: "Нажмите для переключения",
    amPM: ["ДП", "ПП"],
    yearAriaLabel: "Год",
    time_24hr: true,
};

var formioOptions = {
    noDefaultSubmitButton: true,
    language: 'ru',
    builder: {
        basic: {
            title: 'Основные',
            components:
                {
                    textfield: {
                        title: 'Текстовое поле',
                        icon: 'terminal',
                        schema: {
                            type: 'textfield',
                            label: 'Текстовое поле',
                            key: 'textfield',
                            keyModified: true
                        }
                    },
                    textarea: {
                        title: 'Текстовая область',
                        icon: 'font',
                        schema: {
                            type: 'textarea',
                            label: 'Текстовая область',
                            key: 'textArea',
                            keyModified: true
                        }
                    },
                    number: {
                        title: 'Номер',
                        icon: 'hashtag',
                        schema: {
                            type: 'number',
                            label: 'Номер',
                            key: 'number',
                            keyModified: true
                        }
                    },
                    password: {
                        title: 'Пароль',
                        icon: 'asterisk',
                        schema: {
                            type: 'password',
                            label: 'Пароль',
                            key: 'password',
                            keyModified: true
                        }
                    },
                    checkbox: {
                        title: 'Флаг',
                        icon: 'check-square',
                        schema: {
                            type: 'checkbox',
                            label: 'Флаг',
                            key: 'checkbox',
                            keyModified: true
                        }
                    },
                    selectboxes: {
                        title: 'Списки',
                        icon: 'plus-square',
                        schema: {
                            type: 'selectboxes',
                            label: 'Списки',
                            key: 'selectBoxes',
                            keyModified: true
                        },
                    },
                    select: {
                        title: 'Список',
                        icon: 'th-list',
                        schema: {
                            type: 'select',
                            label: 'Список',
                            key: 'select',
                            keyModified: true
                        }
                    },
                    radio: {
                        title: 'Переключатель',
                        icon: 'dot-circle-o',
                        schema: {
                            type: 'radio',
                            label: 'Переключатель',
                            key: 'radio',
                            keyModified: true
                        }
                    },
                    button: {
                        title: 'Кнопка',
                        icon: 'stop',
                        schema: {
                            type: 'button',
                            label: 'Кнопка',
                            key: 'submit',
                            keyModified: true
                        }
                    }
                }
        },
        advanced: {
            title: 'Дополнительные',
            components:
                {
                    email: {
                        title: 'Почта',
                        icon: 'at',
                        schema: {
                            type: 'email',
                            label: 'Почта',
                            key: 'email',
                            keyModified: true
                        }
                    },
                    url: {
                        title: 'Ссылка',
                        icon: 'link',
                        schema: {
                            type: 'url',
                            label: 'Ссылка',
                            key: 'url',
                            keyModified: true
                        }
                    },
                    phoneNumber: {
                        title: 'Телефон',
                        icon: 'phone-square',
                        schema: {
                            type: 'phoneNumber',
                            label: 'Телефон',
                            key: 'phoneNumber',
                            keyModified: true
                        }
                    },
                    tags: {
                        title: 'Теги',
                        icon: 'tags',
                        schema: {
                            type: 'tags',
                            label: 'Теги',
                            key: 'tags',
                            keyModified: true
                        }
                    },
                    address: {
                        title: 'Адрес',
                        icon: 'home',
                        schema: {
                            type: 'address',
                            label: 'Адрес',
                            key: 'address',
                            switchToManualModeLabel: 'Не можете найти адрес? Перейти в ручной режим.',
                            keyModified: true
                        }
                    },
                    datetime: {
                        title: 'Дата и время',
                        icon: 'calendar',
                        schema: {
                            type: 'datetime',
                            label: 'Дата и время',
                            key: 'dateTime',
                            customOptions: {
                                locale: ru
                            },
                            keyModified: true
                        }
                    },
                    day: {
                        title: 'Дата',
                        icon: 'calendar',
                        schema: {
                            type: 'day',
                            label: 'Дата',
                            key: 'day',
                            keyModified: true
                        }
                    },
                    time: {
                        title: 'Время',
                        icon: 'clock-o',
                        schema: {
                            type: 'time',
                            label: 'Время',
                            key: 'time',
                            keyModified: true
                        }
                    },
                    currency: {
                        title: 'Валюта',
                        icon: 'usd',
                        schema: {
                            type: 'currency',
                            label: 'Валюта',
                            key: 'currency',
                            keyModified: true
                        }
                    },
                    survey: {
                        title: 'Опрос',
                        icon: 'list',
                        schema: {
                            type: 'survey',
                            label: 'Опрос',
                            key: 'survey',
                            keyModified: true
                        }
                    },
                    signature: {
                        title: 'Подпись',
                        icon: 'pencil',
                        schema: {
                            type: 'signature',
                            label: 'Подпись',
                            footer: 'Знак вверху',
                            key: 'signature',
                            keyModified: true

                        }
                    }
                }
        },
        layout: {
            title: 'Слои',
            components:
                {
                    htmlelement: {
                        title: 'HTML-элемент',
                        icon: 'code',
                        schema: {
                            type: 'htmlelement',
                            label: 'HTML-элемент',
                            key: 'htmlelement',
                            keyModified: true
                        }
                    },
                    content: {
                        title: 'Контент',
                        icon: 'html5',
                        schema: {
                            type: 'content',
                            label: 'Контент',
                            key: 'content',
                            keyModified: true
                        }
                    },
                    columns: {
                        title: 'Колонки',
                        icon: 'columns',
                        schema: {
                            type: 'columns',
                            label: 'Колонки',
                            key: 'columns',
                            keyModified: true
                        }
                    },
                    fieldset: {
                        title: 'Набор полей',
                        icon: 'th-large',
                        schema: {
                            type: 'fieldset',
                            label: 'Набор полей',
                            key: 'fieldSet',
                            keyModified: true
                        }
                    },
                    panel: {
                        title: 'Панель',
                        icon: 'list-alt',
                        schema: {
                            type: 'panel',
                            label: 'Панель',
                            key: 'panel',
                            keyModified: true
                        }
                    },
                    table: {
                        title: 'Таблица',
                        icon: 'table',
                        schema: {
                            type: 'table',
                            label: 'Таблица',
                            key: 'table',
                            keyModified: true
                        }
                    },
                    tabs: {
                        title: 'Табы',
                        icon: 'folder-o',
                        schema: {
                            type: 'tabs',
                            label: 'Табы',
                            key: 'tabs',
                            keyModified: true
                        }
                    },
                    well: {
                        title: 'Область',
                        icon: 'at',
                        schema: {
                            type: 'well',
                            label: 'Область',
                            key: 'well',
                            keyModified: true
                        }
                    }
                }
        },
        data: {
            title: 'Данные',
            components:
                {
                    hidden: {
                        title: 'Скрытый',
                        icon: 'user-secret',
                        schema: {
                            type: 'hidden',
                            keyModified: true
                        }
                    },
                    container: {
                        title: 'Контейнер',
                        icon: 'folder-open',
                        schema: {
                            type: 'container',
                            label: 'Контейнер',
                            key: 'container',
                            keyModified: true
                        }
                    },
                    datamap: {
                        title: 'Карта',
                        icon: 'th-list',
                        schema: {
                            type: 'datamap',
                            label: 'Карта',
                            addAnother: 'Добавить еще',
                            key: 'datamap',
                            keyModified: true
                        }
                    },
                    datagrid: {
                        title: 'Сетка',
                        icon: 'th',
                        schema: {
                            type: 'datagrid',
                            label: 'Сетка',
                            key: 'datagrid',
                            keyModified: true
                        }
                    },
                    editgrid: {
                        title: 'Редактируемая сетка',
                        icon: 'tasks',
                        schema: {
                            type: 'editgrid',
                            label: 'Редактируемая сетка',
                            removeRow : 'Удалить',
                            key: 'editgrid',
                            keyModified: true
                        }
                    },
                    tree: false
                }
        },
        premium: false
    },
    editForm: {
        textfield:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                },
            ],
        textarea:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        number:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        password:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        checkbox:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        selectboxes:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    components: dataComponents
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        select:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        radio:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    components: dataComponents
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        button:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        /**/
        email:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        url:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        phoneNumber:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        tags:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        address:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                },
                {
                    key: 'provider',
                    label: 'Провайдер',
                }
            ],
        datetime:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    components: [
                        {
                            type: "datetime",
                            key: "defaultValue",
                            customOptions: {
                                locale: ru
                            }
                        },
                    ]

                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                },
                /*{ календари на вкладке Дата в компоненте дата и время перевести нельзя, потому что их ид пересекаются с ид текстовых полей на той же вкладке
                    key: 'date',
                    components: [
                        {
                            type: "datetime",
                            key: "datePicker.maxDate",
                            customOptions: {
                                locale: ru
                            }
                        },
                        {
                            type: "datetime",
                            key: "datePicker.minDate",
                            customOptions: {
                                locale: ru
                            }
                        },
                    ]
                }*/

            ],
        day:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        time:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        currency:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        survey:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        signature:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        /**/
        htmlelement:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        content:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        columns:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        fieldset:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        panel:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        table:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        tabs:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        well:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                    ignore: true
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        /**/
        hidden:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                    ignore: true
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                    ignore: true
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        container:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        datamap:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        datagrid:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ],
        editgrid:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                },
                {
                    key: 'templates',
                    label: 'Шаблоны',
                }
            ],
        tree:
            [
                {
                    key: 'api',
                    // ignore: true
                },
                {
                    key: 'data',
                    label: 'Данные',
                },
                {
                    key: 'validation',
                    label: 'Валидация',
                },
                {
                    key: 'conditional',
                    label: 'Условия',
                },
                {
                    key: 'logic',
                    label: 'Логика',
                    components: logicComponents
                },
                {
                    key: 'layout',
                    label: 'Слой',
                },
                {
                    key: 'display',
                    label: 'Отображение',
                }
            ]
    },
    i18n: {
        ru: {
            'Trigger' : 'Триггер',
            'Type' : 'Тип',
            'Event' : 'Событие',
            'Actions' : 'Действия',
            'Value' : 'Значение',
            'key' : 'Ключ',
            'Property' : 'Свойство',
        }
    }
}

Formio.createForm(formElem, JSON.parse(SchemeAsString), formioOptions)
            .then(function (form) {
            form.nosubmit = true; 
            form.on('submit', function (submission) {
                var dataLabels = {};
                var element = {};
                if(form) {
                    for (var prop in submission.data) {
                        element = form.getComponent(prop);
                        if (element.originalComponent.type != 'button') {
                            if (element.originalComponent.type == 'selectboxes') {
                                dataLabels[prop] = {};
                                dataLabels[prop].valuesLabels = {};
                                dataLabels[prop].label = element.originalComponent.label;
                                element.originalComponent.values.forEach(function (selectBoxElement) {
                                    dataLabels[prop].valuesLabels[selectBoxElement.value] = selectBoxElement.label;
                                });
                            } else {
                                dataLabels[prop] = element.originalComponent.label;
                            }
                        }
                    }

                    submission.sessid = BX.message('bitrix_sessid');
                    submission.dataLabels = dataLabels;
                    submission.data = form?._data;

                    var request = $.ajax({
                        url: '.....',
                        method: 'POST',
                        data: submission
                    });
                    request.done(function (response) {
                        isSubmitting = false;

                        if (response.data.status === 'success') form.resetValue();
                        form.emit('submitDone', submission);
                    });
                }
            });
        });

**Comment by AlexeyDavyd** [comment]
@LenaKis  I have rendered one form two times in two separate HTL elements but was not able to make them submit at once.
![image](https://user-images.githubusercontent.com/47381348/142431550-de065eda-3b41-4586-9163-07c93c592138.png)

Please provide some more specific info on how do you handle yours two forms.

**Comment by LenaKis** [comment]
My fiddler with examle
https://jsfiddle.net/hf1rzjx8/

**Comment by AlexeyDavyd** [comment]
@LenaKis After some investigation I realized that it happens because of same instance of FormioOptions that you pass to createForm method.  I was able reproduce same issue and fix it by creating one more variable for formioOptions2 or using spread to avoid same link to object.

**Comment by LenaKis** [comment]
Thank's! It work!
