### ISSUE TITLE
[QUESTION] When should the onUpdateComponent event in the FormBuilder be triggered?

### ISSUE THREAD

**Issue by crcollver-ats** [formio/react#430]
The description for this event says it's "triggered when a component is added or moved in the form".  From what I can observe, the event is only triggered when the settings dialog is opened or cancelled.  Clicking save in the dialog does not generate this event.  

Furthermore, moving an existing component within the builder does not generate the event.

I'm using `formiojs 4.12.6` and `@formio/react 5.2.0`

I have a feeling I'm misunderstanding something, so I was hoping someone could clarify what this event should be doing.  The onChange event works just fine and is how I'm currently tracking movement in the builder.

Thanks!

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
