### ISSUE TITLE
Add New Templates to Formio

### ISSUE THREAD

**Issue by rafmachado** [formio/react#436]
Hi all, 
I want to add a custom framework, like bootstrap, to formio. I am trying to use Templates, but the struture of my css framework is not the same as formio/bootstrap, for example. 
Is there any way to add my library using/ading new Templates?

@randallknutson

**Comment by test3698741** [comment]
I'm trying to add a component that is devextreme too, but in Formio, I'm under the basic group. When I drag and drop, it doesn't appear in the preview.


@randallknutson
@rafmachado

**Comment by lane-formio** [comment]
Here's an example I received from one of our devs:
[HQScript.txt](https://github.com/user-attachments/files/16339575/HQScript.txt)
