### ISSUE TITLE
New Data to Admin Resource Error

### ISSUE THREAD

**Issue by sdancer75** [formio/react#439]
Entering a new entry to the Admin Resource shows an error bar without a description. 

https://ibb.co/kx2XjfM

This happens when I select from the Action --> [Save Submission] to save submission to "Admin". When it's empty it works.

https://ibb.co/4V7WgnD

Is that normal behavior? As far as I understand the admins should be saved to Admin resource, Users to Users resource, and so on.

Thanx

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
