### ISSUE TITLE
[BUG] Cannot prepopulate provider and key in address component

### ISSUE THREAD

**Issue by Ashakibp** [formio/react#443]
## Environment
Please provide as many details as you can:

While passing in custom components, we are not able to set the `provider` and `params.providerOptions.params.subscriptionKey`

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
FormIO react
- Frontend framework:
NextJs/React
- Browser:
Chrome
- Browser version:

## Steps to Reproduce
1. pass in the `FormBuilder` options a custom address component with the provider and subscription key filled out

**Comment by Ashakibp** [comment]
Just to clarify, this is happening when trying to put a pre-defined address component with the provider and API key

**Comment by edwinanciani** [comment]
@Ashakibp Could you send screenshots of the error you are facing?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
