### ISSUE TITLE
[BUG]  formio Submission Grid column shows [object Object]

### ISSUE THREAD

**Issue by Tzach123** [formio/react#445]
Hello everyone!

In this case, I use with "SubmissionGrid" component and the type field is the "Select" component.
How can I resolve this issue?

![image](https://user-images.githubusercontent.com/64698477/167309793-0c883f61-351b-4e3a-bb02-4f8f61d5adbb.png)

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by BeateBoettcher** [comment]
@jeriah-formio I currently ran over this problem in Version 4.11

**Comment by lane-formio** [comment]
@BeateBoettcher 
I'm sorry, version @formio/react@4.11? I'm having difficulty even finding this version published anywhere.
