### ISSUE TITLE
[BUG] getSubmissions sort filter has no effect

### ISSUE THREAD

**Issue by sdancer75** [formio/react#447]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.3.0
- Formio.js version: 4.14.2
- Frontend framework: 16.8.2
- Browser: chrome
- Browser version: 100.x

## Steps to Reproduce
1.  Use getSubmissions (name, page filter)
2.  As filter use { sort: '-data.newsdatetime' }
3. Submissions are not sorted 

## Expected behavior

To be sorted in a descending order

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
const filter = {
	sort: '-data.newsdatetime',
}

getSubmissions('news', 1, filter, '', (err, result) => {
					if (err === null) {
						console.log('Results=', result, 'Filter=', filter);
					}
				}),




```

**Comment by sdancer75** [comment]
It seems that the offending code at ```src\modules\submissions\actions.js``` ignores any sequential `getSubmissions `  sorting parameters if the initial internal state is missing of this attribute. Why?

```
  const {
    limit,
    query,
    select,
    sort,
  } = selectRoot(name, getState());

  if (sort) {
    requestParams.sort = sort;
  }
  else {
    delete requestParams.sort;
  }
```

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
