### ISSUE TITLE
[BUG] documentation - object passed to 'submission' prop must be named 'data' 

### ISSUE THREAD

**Issue by DaCastle** [formio/react#450]
## Environment
Please provide as many details as you can:

The [JavaScript docs](https://help.form.io/developers/form-renderer#rendering-submissions) show an example, but the react docs do not make it obvious that the `submission` prop needs the object containing the submission values to be named `data`.

As such, my first thought was to just pass my submission key/values like:
`submission={formAnswers.customFields}`

Unfortunately, this also compounded the issue as it appears the react component _**mutates**_ the passed in object as opposed to making a copy to work with internally.

All in all, just adding clarity arouund the expected object shape needing to look like this:

`submission={{ data: formAnswers.customFields }}`

Would have saved me some headache this morning (:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
    "@formio/react": "^5.2.1",
    "formiojs": "^4.14.6",
- Frontend framework:
    "react": "^16.8.6",

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
