### ISSUE TITLE
[BUG] signature component not working for mobile with PDF display mode

### ISSUE THREAD

**Issue by chan9948** [formio/react#452]
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.14.7
- Frontend framework: react 18.1.0
- Browser: chrome
- Browser version: 101.0.4951.67

 Signature component cannot be draw on mobile with PDF display mode , but works with form view mode.

console log showing "Unknown plugin option widgets"

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
