### ISSUE TITLE
[BUG] Losing data when re-rendering the form with custom components

### ISSUE THREAD

**Issue by joaotalegria** [formio/react#455]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.14.7
- @formio/react: "5.2.3,
- Frontend framework: React v.17.0.2
- Browser: chrome
- Browser version: 102.0.5005.63

## Description
1. Giving a wizard with 3 pages, all of them with custom-components
2. The data inserted on them is persisted on a Database (AWS Dynamo)
3. When I try to re-render the form and passed the saved data within submission object on Form Component, the custom components have a value for a second, and after that, they re-render with null value.

## Expected behavior
- On re-render the form, components should keep their value

## Observed behavior
- As mentioned on Description 3)

**Comment by elias-soykat** [comment]
@joaotalegria  Could you share a codesandbox or jsfiddle for better understand.

**Comment by Benzer1406** [comment]
Happens to me to. Have a custom component in a formio wizard. When I fill out the custom component, click on next, and then go back, the data of the custom component is gone.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by dinbtechit** [comment]
This is still an issue. Custom component not maintaining the enteredinformation when you click `next.`
