### ISSUE TITLE
[BUG] Form components edit grid 

### ISSUE THREAD

**Issue by iyyappanrock535** [formio/react#466]
Form components I'm using edit grid json. But the edit grid single row edit and delete icon available. But i click the delete button what events i will use in the react formio?

**Comment by TanyaGashtold** [comment]
@iyyappanrock535 , the 'editGridDeleteRow' event is emitted on editGrid row delete. Unfortunately, this event does not present in event options for @react/formio and if you use TypeScript it can give an error. As a workaround you can catch this event in formReady like this:

```
   <Form
        form={form}
        submission={submission}
        formReady={(instance)=> {
          instance.on('editGridDeleteRow', () => {...} )
        }}
      />
```
