### ISSUE TITLE
Reading moment version issue

### ISSUE THREAD

**Issue by boussadjra** [formio/react#470]
## Environment
Node v16.13.2
vite 3.0.3
 

- Hosting type

  - [x ] Local deployment

- Version: 
- Formio.js version: 4.13.4
- Frontend framework: React (antd)
- Browser: google chrome
- Browser version: 105.0.5195.127

## Steps to Reproduce
1. intallation of @formio/react & formiojs
2. adding the basic example
3. running the example in the browser 

## Expected behavior
Showing the basic form `<Form src="https://example.form.io/example" onSubmit={console.log} />`
## Observed behavior

Getting an error related to moment-timezone : 
![image](https://user-images.githubusercontent.com/11801238/191182598-b19a9a4c-17ae-409f-9791-92b138aa648d.png)

**Comment by damnitrahul** [comment]
@boussadjra How did you solve this issue?
