### ISSUE TITLE
[BUG] OnCancel prop dosent work properly and its not mentioned in the documentation

### ISSUE THREAD

**Issue by AyoubSayah** [formio/react#472]
We have an issue using wizard we wanted to override cancel button behavior, but when we set our implementation into the OnCancel() callback doesn't work even the event did not dispatch.
The only workaround to override is to get the Form instance, then override his property function cancel() and I am not sure if it's gonna make problems later or not!.
[image](https://user-images.githubusercontent.com/57968451/192496458-61c8c0fd-fef6-4a7e-b12d-26e8e5086213.png)

**Comment by TanyaGashtold** [comment]
Thanks for reporting the issue. We checked and the "Cancel" event is indeed not fired. We may need to remove it from @formio/react. Your workaround is expected to work fine.
