### ISSUE TITLE
[BUG] Support for Custom Components React 18.x

### ISSUE THREAD

**Issue by jake-pharr** [formio/react#474]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ x ] Local deployment
    - Version: 
- Formio.js version: "^4.14.8"
- Frontend framework: "react": "^18.1.0", "@formio/react": "^5.2.4-rc.1",
- Browser: Any
- Browser version: Any

## Steps to Reproduce
1. Implement custom Formio Component as checkmatrix.js example
2. 
3. 

## Expected behavior
Working Custom component in React 18 
## Observed behavior
React goes into Warning using ReactDOM
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by brendanbond** [comment]
Hi @jake-pharr, thanks for reaching out. This has to do with an update to React 18's client rendering APIs. You'll see this warning until you change `ReactDOM.render()` function to React 18's new render API `createRoot`. Please see [this link](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).

**Comment by brendanbond** [comment]
@jake-pharr I might have misunderstood your issue here, let me take a look when I get a moment and get back to you ASAP
