### ISSUE TITLE
[BUG] Receive 'Not Authorised' when using Custom JWT Authentication

### ISSUE THREAD

**Issue by jasonsegal23** [formio/react#478]
## Environment
We are running with the following setup:
- Local FormIO Server
- NodeJS API (Authenticates with IDS + Serves FormIO Token)
- React Web App (Rendering FormIO Form using '@formio/react')

## Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - **FormIO** Version: 3.0.0-rc.10
    - **@formio/react** Version: 5.2.4-rc.1
    - **formiojs** version: 4.14.9
    - Frontend framework: React
    - Browser: Chrome
    - Browser version: 107

## Steps to Reproduce
1. Login + Add FormIO JWT token (formioToken) to Local Storage
2. Load FormIO form
3. Make FormIO request 
4. Receive 'Not Authorised' error message

## Expected behavior
'formioToken' should remain in local storage and Web App should be allowed to make requests to FormIO.

## Observed behavior
'formioToken' is removed from local storage once the Form is loaded and the Web App is now not authorised to make requests to FormIO.

## Additional Information
Our Custom JWT auth worked with 'react-formio' v3 ('formiojs' v3). However when we moved to 'react-formio' v4 or '@formio/react' v4/5 (all using 'formiojs' v4) this bug appeared.

Our 'formioToken' is successfully placed into Local Storage, however when we load a form the 'formio.js' code errors out with 'Bad Token' here:
![image](https://user-images.githubusercontent.com/56255251/198546468-6e355b5e-bb0b-4c55-b757-33b429caf734.png)

The token is then removed immediately from local storage and any subsequent FormIO requests are unauthorised.

I believe it is the same issue as the one this [PR](https://github.com/formio/formio.js/pull/4757) is trying to solve

**Comment by buecki2018** [comment]
Possible solved, but we just had the same problem and solved it by checking the setting of the apiurl in the Formio Setup. Because it was not set, the request for cecking the token goes to https://api.form.io/current. And at this endpoint the token validaten failed.
When we add sth like that:
`Formio.setApiUrl(apiUrl);`
where apiUrl contains the url of the correct formio Server, the error does not occur, and all things are working fine.

**Comment by NeilRiver** [comment]
@buecki2018 can you show how you used it?

**Comment by buecki2018** [comment]
Not exactly, because i am not longer  involved in  project. But i remember that i simply do the `Formio.setApiUrl(apiUrl);` before using the Formio package.

And i think possible the error isn't still exist, because its one year ago?

**Comment by daneformio** [comment]
@jasonsegal23 are you still reproducing this issue on the latest versions?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
