### ISSUE TITLE
Premium component like Tagpad , Sketchpad are not available 

### ISSUE THREAD

**Issue by aryanisml** [formio/react#480]
I am using formio/react formbuilder. I am not able to see the mention two premium component tagpad and sketchpad.
is any way to enable or visible this two component ??? Or we need to buy the form io for premium component ?

**Comment by mikekotikov** [comment]
@aryanisml to be able to use Tagpad and Sketchpad components you'll need the `@formio/premium` package in your app. This package is available on paid basis. If you need more info on this, please contact `sales@form.io`.
