### ISSUE TITLE
formio object returns null value while updating to @formio/react

### ISSUE THREAD

**Issue by abilpraju-aot** [formio/react#486]
Hi,
I am currently using the "react-formio": "^4.3.0" package and "formiojs": "^4.14.0" .while updating to the new package "@formio/react": "5.2.3" with "formiojs": "^4.14.6". The formio object returns a null value. Any help would be appreciated
![image](https://user-images.githubusercontent.com/83952803/202092978-937b9c84-a919-42b5-9b22-f568c161e3b8.png)

**Comment by aryanisml** [comment]
Do you have any code sandbox or any link where we can see the code.

**Comment by abilpraju-aot** [comment]
I have faced this issue above "@formio/react": "5.0.0" version and no sandbox environment I have tested on my local machine. Thank you
