### ISSUE TITLE
React DataGrid example for Data Binding

### ISSUE THREAD

**Issue by Kunalp3127** [formio/react#494]
Can you provide an example of a data grid implementation using React, with a focus on how to bind data to the Datagrid?

**Comment by govind15496** [comment]
Hey I am a newcomer in this project and I would like to contribute

**Comment by mikekotikov** [comment]
@Kunalp3127 one of the variants you may consider to get the value of DataGrid component in your React component:

`
**const dataGridRef = useRef();
const [dataGridValue, setDataGridValue] = useState([]);**

<Form
        form={form}
        submission={submission}
        url={url}
        options={options}
        hideComponents={hideComponents}
        onSubmit={onSubmit}
        **formReady={(form)=> {
          dataGridRef.current = form.getComponent('dataGrid');
        }}
        onChange={()=>{
          if (dataGridRef.current){
           setDataGridValue(dataGridRef.current.dataValue);
          }
        }}**
 />
`
