### ISSUE TITLE
Is there any way to get an active tab or do I get a callback when I change the tab?

### ISSUE THREAD

**Issue by nitesh-sharecare** [formio/react#496]
Is there any way to get an active tab or do I get a callback when I change the tab?

**Comment by mikekotikov** [comment]
@nitesh-sharecare can you please specify:
1) what tab you're mentioning? Is it about Tabs component?
2) can you please describe your use case in more detail?

**Comment by mialma-Eus** [comment]
Hi, I solved it via Javascript document.getElementsByClassName('nav-link active')[0].href.indexOf('tab1') > 0 -> Tab1 is active ...
Best regads.
