### ISSUE TITLE
Is there anyway to prevent submission with onSubmit event?

### ISSUE THREAD

**Issue by sdancer75** [formio/react#497]
I want to verify if the user wants actually to submit his form. If his response is negative I want to cancel the submission. Is that possible?

ie 

```
<Form
  src="http://xyz"
 onSubmit={event => {
	//cancel submission here
}}
/>
```

**Comment by brendanbond** [comment]
I would pass the [beforeSubmit hook](https://help.form.io/developers/form-renderer#hooks) to the options object

**Comment by sdancer75** [comment]
Thanks, 

Does react component support this event? 

Under React Form Event Props, there is no `beforeSubmit ` property. 
https://github.com/formio/react#event-props

How to implement using class-oriented components (the old style)?

**Comment by brendanbond** [comment]
It's [form renderer option](https://help.form.io/developers/form-renderer#form-renderer-options) that you'd pass via the `options` prop

**Comment by sdancer75** [comment]
I am not sure if I can apply this to React form. Can you give me an example?

**Comment by brendanbond** [comment]
[here you go](https://codesandbox.io/s/throbbing-dew-n8h8cf?file=/src/App.js)

**Comment by sdancer75** [comment]
> [here you go](https://codesandbox.io/s/throbbing-dew-n8h8cf?file=/src/App.js)

Excellent, Thanks.

**Comment by brendanbond** [comment]
@boni-minimum [here you go](https://codesandbox.io/p/sandbox/react-formio-dksfcy)
