### ISSUE TITLE
Data source type

### ISSUE THREAD

**Issue by Agampreet0001** [formio/react#514]
**when data source type selected as URL than dynamic options list is shown in ui but not getting populated in json.**

<img width="910" alt="image" src="https://github.com/formio/react/assets/137164399/ad48d31e-12fc-4acd-9573-16684655de89">

**Comment by daneformio** [comment]
@Agampreet0001 Are you still able to reproduce this in the latest versions?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
