### ISSUE TITLE
Hidden key not Working

### ISSUE THREAD

**Issue by Agampreet0001** [formio/react#515]
<img width="893" alt="image" src="https://github.com/formio/react/assets/137164399/ab96fb47-49a6-4495-b268-8928ce9f8d67">
h

**Hidden is true but still it is visible in the form and conditional logic is also not working.**

**Comment by Agampreet0001** [comment]
sure

**Comment by unnatijadhav** [comment]
Can you let me know the how to start app, I can't find contributing.md file.
I tried npm install, then npm start doesnt start the app

**Comment by gyanendrasinghpanwar** [comment]
I presume, you have added conditional on this field. Condition is true and which is over riding hidden behaviour.

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
