### ISSUE TITLE
Translating FormEdit

### ISSUE THREAD

**Issue by PatrikTrefil** [formio/react#522]
Labels in FormEdit such as [this one](https://github.com/formio/react/blob/c966dd1d93d1ee5b5610496e2578ebc9ce153eb6/src/components/FormEdit.jsx#L63C77-L63C82) should be passed through i18next to allow for translations. The same goes for placeholder values.

 I am willing to make a PR. I just need confirmation that this change is desired.

**Comment by brendanbond** [comment]
PRs are welcome, but this library is a wrapper around our [core Javascript renderer](https://github.com/formio/formio.js), any translations (including labels) already occur there. If there's a specific issue you're running into, please provide a minimally reproducible example. Thanks!

**Comment by PatrikTrefil** [comment]
The `FormEdit` component renders a `FormBuilder` and some extra input fields such as Title, Path, etc. The extra fields can't be translated. As you can see [on this line](https://github.com/formio/react/blob/c966dd1d93d1ee5b5610496e2578ebc9ce153eb6/src/components/FormEdit.jsx#L63C77-L63C82) the label has value `"Title"`, which is a string constant rather than something passed through an internalization library.

Minimally reproducible example: User of this library can not translate the label Title, which is rendered by the `FormEdit` component (this is not handled by the core JS render).

**Comment by brendanbond** [comment]
Ah, I see what you mean. Yeah, I'd happily review a PR for this.

**Comment by PatrikTrefil** [comment]
Please review the PR I made.

**Comment by brendanbond** [comment]
hey @PatrikTrefil see my comments

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
