### ISSUE TITLE
ReferenceError: navigator is not defined in Nextjs

### ISSUE THREAD

**Issue by upfounders** [formio/react#536]
I am creating form with formio in Nextjs project got this error, anyone see this problem, and any workaround?

error - ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/kilghar/Documents/Code/uf-next/node_modules/formiojs/components/file/File.js:120:21)

**Comment by enkinduweles** [comment]
I have the same problem, even using the 'use client' directive of nextjs.

**Comment by Dalorzo** [comment]
If you force the load the form dynamically and avoid any SSR, you will get rid of that problem.

```react
import dynamic from 'next/dynamic'

const Form = dynamic<FormioFormProps>(() => import('@formio/react').then(mod => mod.Form), {
  ssr: false,
  loading: () => <p>Loading...</p>,
})
```

You continue using your form like you usually do

```
/*your commponent*/
return ( <Form
          formReady={onFormReady}
          options={options} .....
          
```

**Comment by lane-formio** [comment]
Thanks for the contribution @Dalorzo.
I'm going to go ahead and close this issue.
