### ISSUE TITLE
adding custom component to formio .

### ISSUE THREAD

**Issue by M-r-hydra** [formio/react#541]
hi , i was trying to add some HTMLelements as a custom component react , but i can not find a good document about it .
so , i Tried to create a custom HTML component with your side bar and save the result object to a constant and tying to store it in state of the last element of components array in form source .

now i want to current operation be automatically and start from the form Builder sidebar . how can i do it ?

i hope this issue helps me for creating this feature .

my code : 

export const persianDatePicker = (className?: string) => ({
  label: "تقویم فارسی",
  labelPosition: "top",
  placeholder: "",
  description: "",
  tooltip: "",
  prefix: "",
  suffix: "",
  widget: {
    type: "input",
  },
  inputMask: "",
  displayMask: "",
  applyMaskOn: "change",
  allowMultipleMasks: false,
  customClass: className || "",
  tabindex: "",
  autocomplete: "",
  hidden: false,
  hideLabel: false,
  showWordCount: false,
  showCharCount: false,
  mask: false,
  autofocus: false,
  spellcheck: true,
  disabled: false,
  tableView: true,
  modalEdit: false,
  multiple: false,
  persistent: true,
  inputFormat: "plain",
  protected: false,
  dbIndex: false,
  case: "",
  truncateMultipleSpaces: false,
  encrypted: false,
  redrawOn: "",
  clearOnHide: true,
  customDefaultValue: "",
  calculateValue: "",
  calculateServer: false,
  allowCalculateOverride: false,
  validateOn: "change",
  validate: {
    required: false,
    pattern: "",
    customMessage: "",
    custom: "",
    customPrivate: false,
    json: "",
    minLength: "",
    maxLength: "",
    strictDateValidation: false,
    multiple: false,
    unique: false,
  },
  unique: false,
  errorLabel: "",
  errors: "",
  key: "textField",
  tags: [],
  properties: {},
  conditional: {
    show: null,
    when: null,
    eq: "",
    json: "",
  },
  customConditional: "",
  logic: [],
  attributes: {
    "data-jdp": "true",
  },
  overlay: {
    style: "",
    page: "",
    left: "",
    top: "",
    width: "",
    height: "",
  },
  type: "textfield",
  input: true,
  refreshOn: "",
  dataGridLabel: false,
  addons: [],
  inputType: "text",
  id: `el86fr${Date.now()}`,
  defaultValue: "",
});

when i call this function , it returns an Object for a custom HTML component and i append it to state , i want to move this calling function to FormBuiler Component like other components . 

Im using react 18.2 with TypeScript .
my formio dependency version is :

    "@formio/react": "^5.2.4-rc.1",
    "formiojs": "^4.15.1",

thanks a lot for help ❤

**Comment by Dalorzo** [comment]
These examples helped me answer most of my questions. I wonder if it is what you are looking for

https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by sabato-galasso** [comment]
An example updated React 18 + Custom Component working! [Demo](https://codesandbox.io/p/sandbox/distracted-butterfly-rzy27w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkqdkr900063b6moebba57e%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.435798934026685%252C46.564201065973315%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkqdkr800023b6mrxlx7mve%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800013b6mpvc2ylsd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FCustom%252FfirstName.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%252C%2522activeTabId%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%257D%252C%2522clvkqdkr800053b6mmkie1eqn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%252C%2522activeTabId%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%257D%252C%2522clvkqdkr800033b6m4btu9sqj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by CodeFox1119** [comment]
> An example updated React 18 + Custom Component working! [Demo](https://codesandbox.io/p/sandbox/distracted-butterfly-rzy27w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkqdkr900063b6moebba57e%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.435798934026685%252C46.564201065973315%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkqdkr800023b6mrxlx7mve%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800013b6mpvc2ylsd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FCustom%252FfirstName.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%252C%2522activeTabId%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%257D%252C%2522clvkqdkr800053b6mmkie1eqn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%252C%2522activeTabId%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%257D%252C%2522clvkqdkr800033b6m4btu9sqj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Could you please help me typescript version?

**Comment by sabato-galasso** [comment]
> > An example updated React 18 + Custom Component working! [Demo](https://codesandbox.io/p/sandbox/distracted-butterfly-rzy27w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkqdkr900063b6moebba57e%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.435798934026685%252C46.564201065973315%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkqdkr800023b6mrxlx7mve%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800013b6mpvc2ylsd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FCustom%252FfirstName.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800023b6mrxlx7mve%2522%252C%2522activeTabId%2522%253A%2522clvkrzvvx001q3b6mbxlpnvbb%2522%257D%252C%2522clvkqdkr800053b6mmkie1eqn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkqdkr800053b6mmkie1eqn%2522%252C%2522activeTabId%2522%253A%2522clvkqdkr800043b6mwn6lyush%2522%257D%252C%2522clvkqdkr800033b6m4btu9sqj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkqdkr800033b6m4btu9sqj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
> 
> Could you please help me typescript version?
do you already have a starting example?

**Comment by ryanhs** [comment]
hi all,

i have manage this to achieve with typescript , let me know if its working in yours.

https://codesandbox.io/p/devbox/formio-typescript-custom-component-zxylsq
