### ISSUE TITLE
Icons not working as expected

### ISSUE THREAD

**Issue by kaaviya-min** [formio/react#573]
**Describe the bug**
Icons on the Form.io forms are not rendering properly in the React application. The expected Font Awesome icons are either missing or not displaying as intended, which affects the user interface and experience.

**To Reproduce**
Steps to reproduce the behaviour:

- Below are the imports for `Form.io` component used in `.scss`
1. @import "bootstrap/dist/css/bootstrap.css";
2. @import "formiojs/dist/formio.full.min.css";
3. @import '@fortawesome/fontawesome-svg-core/styles.css'

Package.json
`@formio/react: "^5.3.0-rc.3"`
`@fortawesome/fontawesome-free: "^6.5.2"`
`"formiojs": "^4.19.3"`

**Expected behavior**
The icons should render correctly as per the Form.io form definition, with the appropriate Font Awesome icons visible for the specified fields (e.g., Edit icon for text fields, Delete icon for Cancel items).

What am i missing?

**Screenshots**

1. Expectations Vs Application
<img width="103" alt="Screenshot 2024-08-13 at 11 01 44 AM" src="https://github.com/user-attachments/assets/69613ecd-c208-43fc-a4b4-fa09e3a3fbe6">

<img width="91" alt="Screenshot 2024-08-13 at 11 00 11 AM" src="https://github.com/user-attachments/assets/9f0edda2-9db9-467b-ad8d-ea729493d394">

**Desktop (please complete the following information):**
-   Browser [e.g. chrome, safari] -  In all browsers

**Comment by kaaviya-min** [comment]
@brendanbond

**Comment by ksachin7** [comment]
To address the issue with Font Awesome icons not rendering in Form.io forms in your React application, provide detailed code samples to understand and debug the problem effectively.

**Comment by kaaviya-min** [comment]
Closing this.

this caused because application's Font was blocking the formio's icons
