### ISSUE TITLE
index.js:295 Validator error: Failed to validate available values in select component 'action': data source url is not valid}

### ISSUE THREAD

**Issue by NexPlex** [formio/react#575]
Describe the bug
I downloaded this https://github.com/formio/formio

"name": "oss-portal",
"version": "0.0.1",
"main": "index.js",
"author": "brendanjbond <brendanbond@gmail.com>",
"license": "MIT",
"dependencies": {
    "@formio/js": "5.0.0-dev.5621.91bd945",
    "@formio/react": "6.0.0-dev.568.ced0fbd",
    "bootstrap": "^5.3.3",
    "bootstrap-icons": "^1.11.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remixicon": "^4.2.0",
    "wouter": "^3.1.2"
},
"devDep
"name": "formio",
"version": "4.0.0",
"description": "The formio server application.",
"license": "OSL-3.0",
"main": "index.js",
"dependencies": {
"@formio/core": "2.1.0-dev.129.a4f2d55",
"@formio/js": "5.0.0-dev.5673.3d062b9",
"@formio/node-fetch-http-proxy": "^1.1.0",
"@formio/vm": "1.0.0-dev.32.0743021",
"@popperjs/core": "^2.11.8",

loaded using the docker container script.

The app is running here https://form.empowerhope.ai/

The default username and password are still in place if you want to check it out.

Issue: 
Open any form for editing. On the Form Actions tab, select an action from the dropdown.
In the console window, I immediately get the error below. The + Add Action button does not do anything.

 "index.js:295 Validator error: Failed to validate available values in select component 'action': data source url is not valid}"
 
 I have not been able to identify a patch for this issue.

Thank you
Chris

**Comment by lane-formio** [comment]
Have you tried one of the tagged versions of formio? 
4.2.2 is our latest official release and 4.3.0-rc.11 is our most recent rc.

**Comment by NexPlex** [comment]
Hi @lane-formio  thank you that worked. Any suggestion on https://github.com/formio/react/issues/574
